- .eslintrc.json
- 절대경로를 쓰도록 `../`을 사용하면 에러가 나게 만들었습니다.
> Feature/#9 ESLint prefer absolute path 세팅

- src/App.tsx
- src/api/bus/APIDetail.ts
- src/api/bus/entity.ts
- src/api/bus/index.ts
- src/api/index.ts
- src/index.scss
- src/pages/BusPage/BusLookUp/BusLookUp.module.scss
- src/pages/BusPage/BusLookUp/index.tsx
- src/pages/BusPage/BusTimetable/index.tsx
- src/pages/BusPage/hooks/useBusDirection.ts
- src/pages/BusPage/hooks/useBusLeftTime.ts
- src/pages/BusPage/index.tsx
- src/pages/BusPage/ts/busModules.ts
- src/pages/BusPage/ts/busTimeModules.ts
- src/static/bus.ts
버스페이지 상단 카드 영역을 추가했습니다.
- 메인페이지 영역에서 경로 별 버스 정보를 조회할 것을 대비해 **`[셔틀, 대성, 마을]`** 순으로 출발지(`departList`)와 목적지(`arrivalList`)를 받습니다.
- 최소 1분에 한번씩은 조회하도록 `staleTime`과 `refetchInterval`을 설정했습니다.
- 미운행인 구간에 대해서는 API가 에러를 반환하는데(천안역 -> 야우리 등), 해당 부분은 `remain_time`에 `'미운행'`을 담고 있는 `emptyRouteData`를 반환하도록 만들었습니다. UI를 작성하는 부분에 있어서 편의를 위해 이렇게 작성했는데, 더 나은 방안이 생각난다면 추천 부탁드립니다.
추가로, 글꼴이 정확히 나오지 않고 있는 문제가 있어 `-webkit-font-smoothing: antialiased;`를 전역으로 추가했습니다.
> [버스 페이지] 상단 카드 영역 및 상태 관리 로직 추가

- src/App.tsx
- src/components/common/Header/index.tsx
- src/pages/BusPage/ts/busModules.ts
- src/pages/IndexPage/IndexPage.module.scss
- src/pages/IndexPage/components/IndexBus/IndexBus.module.scss
- src/pages/IndexPage/components/IndexBus/hooks/useIndexBusDirection.ts
- src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
- src/pages/IndexPage/components/IndexBus/index.tsx
- src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
- src/pages/IndexPage/components/IndexCafeteria/index.tsx
- src/pages/IndexPage/components/IndexNotice/IndexNotice.module.scss
- src/pages/IndexPage/components/IndexNotice/index.tsx
- src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
- src/pages/IndexPage/components/IndexStore/index.tsx
- src/pages/IndexPage/components/IndexTimetable/IndexTimetable.module.scss
- src/pages/IndexPage/components/IndexTimetable/index.tsx
- src/pages/IndexPage/index.tsx
- src/static/category.ts
- src/static/storeCategory.ts
메인페이지에 필요한 주변식당 카테고리 목록과, 버스 컴포넌트를 추가했습니다.
메인페이지에 각 컴포넌트에 공간을 할당해두었으니, 추후에 시간표 / 식당 / 공지사항도 추가해주세요.
최대한 기존 페이지에 존재하는 훅과 static 데이터를 활용했고, 이 과정에서 몇가지 리팩토링을 진행했습니다.
- 카테고리에 존재하는 헝가리안 표기법 레거시를 제거했습니다
- 전체가 추가되며 바뀐 카테고리에 맞추다보니 프로덕션과 카테고리 아이템 정보가 달라졌습니다.
- 버스 캐러셀 UI 조작 방식을 중복되는 부분만 제거하고 유지했습니다.
- 버스의 상태를 다루는 부분은 최적화를 진행했습니다.
- 데이터는 `[셔틀, 대성, 시내]` 순서로 가지고있고, 모바일의 경우 UI 표시 순서를 `mobileBusTypes`로 가져 둘 간의 동기화를 위해 `matchToMobileType`함수를 사용합니다.
> [메인 페이지] 주변식당 카테고리, 버스 컴포넌트 추가

- src/App.tsx
- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/api/auth/index.ts
- src/components/TimetablePage/DefaultPage/index.tsx
- src/components/common/Header/Header.module.scss
- src/components/common/Header/index.tsx
- src/pages/Auth/LoginPage/index.tsx
- src/utils/hooks/useTokenState.ts
- src/utils/recoil/index.ts
- `login` API의 Response entity가 변경된 것을 적용했습니다.
- `refresh` API가 추가되어, 클래스를 정의했습니다.
- refreshToken을 localStorage에 저장하게끔 수정했습니다.
- 기존에 사용하던 `tokenState` 대신, 해당 데이터를 불러와 없을 경우 refresh를 거쳐 토큰을 반환하는 selector(`tokenStateQuery`) 를 추가했습니다.
- 해당 selector는 refresh요청 이후에 데이터를 반환해야 하므로, `useRecoilValueLoadable` 을 활용한 훅(`useTokenState`)으로 감싸 데이터를 반환하게 만들었습니다.
- `useRecoilValueLoadable` 은, suspense를 지원해 해당 데이터의 로딩까지 Suspense를 동작시켜 화면 깜빡임 등이 발생하지 않습니다.
- token set 동작은 기존처럼 `useSetRecoilValue(tokenState)`를 가져다 활용하셔도 `useTokenState`의 selector가 해당 아톰을 읽어 반환하기에 문제없습니다.
고민해볼 점은,
- `useTokenState`의 반환이 `string` 타입으로 고정된 상태라 훅의 의도와 맞추려면 `null | string` 으로 바꿔야 할 것 같은데, 해당 토큰을 사용하고 있는 로직들의 타입이 string 고정이라, 고려하지 못한 상태입니다.
- 해당 API들의 타입을 바꿔야 하는지, 토큰을 string 고정으로 바꾸며 로그인이 필요한 라우팅을 고정해야하는지 등을 고민해보면 좋을 것 같네요.
- **로그인 …
> 자동로그인 기능 추가

- src/assets/svg/right-arrow.svg
- src/pages/IndexPage/components/IndexNotice/IndexNotice.module.scss
- src/pages/IndexPage/components/IndexNotice/index.tsx
`IndexPage` 컴포넌트 중 공지사항 컴포넌트를 추가했습니다.
- 공지사항 목록 페이지에서 사용한 `useArticleList()` 훅을 사용해 UI 맞게 길이만큼 잘라 그리게끔 만들었습니다.
> [메인페이지] 공지사항 컴포넌트 추가

- src/pages/BusPage/ts/busModules.ts
현재 시간을 밀리초 단위로 더해 버스 도착 시간을 계산하도록 변경했습니다.
(기존 방식: 현재 시, 분만을 합산하여 계산하는 방식)
> [버스 페이지] 시간 표시 오류 수정

- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/pages/Auth/SignupPage/hooks/useSignup.ts
- src/pages/Auth/SignupPage/index.tsx
- 회원가입 POST 기존 path `user/register` => `user/student/register`
- `identity` 프로퍼티 삭제
- gender request type `number`로 변경
- 성별 선택시 0과 1로 나타나는 오류 수정
- 에러별로 핸들링 할 수 있도록 변경
예) 이메일 중복일시 에러 메시지 변경
딱히 테스트할만한 koreatech 아이디가 없어서, 이메일 인증 로직까지는 체크하지 못했습니다.
이부분에 대한 테스트는 QA시점으로 넘기거나, 계정을 삭제하고 다시 인증해야할것같습니다.
> [Auth] 회원가입 API 변경사항 대응

- src/pages/IndexPage/components/IndexCafeteria/index.tsx
모바일환경에서 더보기 이벤트가 없어 다른 날, 다른 시간 식단표를 확인 할 수 없는 문제를 수정했습니다.
https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/51395707/200039fd-a0b7-4a00-bdf9-9dfa3be6c30e
- Close #76
> [식단 페이지] 모바일 환경에서 식단 더보기 이벤트 추가

- src/pages/IndexPage/components/IndexTimetable/index.tsx
- 기능 : 메인 페이지의 시간표에서 같은 강의 시간이 표시되는 것을 삭제
- issue : #116
> [시간표] 메인 페이지의 시간표에서 같은 강의 시간 표시 삭제

- .github/workflows/CHECK_PR_MERGED.yml
- .github/workflows/PICK_REVIEWER.yml
- Close #118
PR이 병합될 때 삐봇서버로 PR링크를 보냅니다.
아직은 인터널에서 대응되지 않아 서버 동작이 없지만, 추후 해당 링크를 읽어서
PR이 만들어지는 순간에 인터널 서버에 저장해둔 PR링크를 토대로,
병합된 PR의 경우엔 `#frontend_github` 채널에서 해당 메시지를 다르게 보일 수 있도록 수정할 예정입니다.
> [편의] 병합 시 삐봇 서버에 요청 추가

- src/components/TimetablePage/DefaultPage/index.tsx
- Close #143
- 기능 : 
- issue : #143 
- 학부 선택 메뉴의 학부명을 개설학부에 있는 학부명과 일치하도록 했습니다.
- 추가로, 교과목 검색 시 영어 대소문자를 구분하지 않도록 했습니다.
> [시간표] 강의 검색 시 학부 필터링 미작동하는 학부 수정

- src/global.d.ts
- src/pages/Auth/LoginPage/index.tsx
- src/utils/ts/sendClientError.ts
- Close #151 
- 기능 : 클라이언트 에러 처리 추가
- issue : #151 
- 클라이언트 에러 처리를 추가했습니다.
- `sendClientError()` 유틸 함수를 추가했습니다.
- usage 예시는 로그인쪽에 추가해두었습니다. 
- 에러는 삐봇 클라이언트 에러 api 로 post 됩니다.
- 전역 에러 타입 추론을  'unknwon`  기본값으로 지정했습니다.
삐봇 알림 예시)
> [공통] 클라이언트 에러 처리

- src/components/common/LogPage/index.tsx
- src/pages/Store/StoreDetailPage/index.tsx
- Close #102
- 기능 : GA 전화번호 로깅 기능 및 userID 쿠키 저장
- issue : #102 
현재 userID가 계속 호출되는 형태로 userID를 저렇게 넣는 것은 별 의미가 없다고 생각되어서 userID를 초기 생성시 쿠키에 저장하고 지속적으로 사용시 업데이트 될 수 있도록 로직을 수정하였습니다. 또한 GA에 대한 전화번호 로깅을 추가하였습니다.
Main에 즉시 나가야하는 부분이라 main hotfix로 넣겠습니다.
> [GA] 전화번호 로깅 기능 추가 및 userID 쿠키 저장

- src/pages/IndexPage/components/IndexNotice/IndexNotice.module.scss
- src/pages/IndexPage/components/IndexNotice/index.tsx
- Close #157 
- 기능 :  css로 max-width 를 세팅했고 더 길어지는 것을 방지하고 길어질시 ... 처리를 했습니다.
- issue : #157 
현재
> [메인 페이지] 공지사항 텍스트 오버 처리

- src/components/TimetablePage/DefaultPage/index.tsx
- src/components/TimetablePage/Listbox/index.tsx
- src/components/common/Header/index.tsx
- src/pages/IndexPage/components/IndexTimetable/index.tsx
- Close #240 
- 기능 : 유저팀 시간표 로깅 추가
- issue : #240
유저팀 웹 시간표 로깅 추가했습니다. [유저팀 로그 시트](https://docs.google.com/spreadsheets/d/1gdM4oX3t6LTOfC1Dkrc5Bwnfm-0jTyAzmflnvGnnMss/edit#gid=607823791)
유저팀 로그 시트 중 **앱 로그** 는 main 브랜치에 기능이 추가되어 있지 않아 **앱 로그**는 배포 후 로그를 추가할 예정입니다.
(`(앱) 시간표_학기 드롭다운_전체 클릭` 과 `(앱) 시간표_이미지 저장_클릭`만 추후 추가하도록 하겠습니다.)
공통으로 사용하는 ListBox에 새로운 속성인 `logTitle`이 추가되었습니다. 이 부분을 중점적으로 리뷰해주시면 감사하겠습니다!
> [유저] 시간표 로깅 추가

- src/components/TimetablePage/LectureTable/index.tsx
- src/components/TimetablePage/Timetable/Timetable.module.scss
- src/components/TimetablePage/Timetable/index.tsx
- 기능 : [시간표] 시간표 2차 스프린트 이슈 해결 (강의 정보, 타임테이블)
- issue : #248 
- 시간표 상단 탭 이름 옆 세모 모양이 내림차순/ 오름차순 정렬할 수 있도록 하는 버튼 삭제
- 시간표 타임테이블 시간 가운데 정렬
- 시간표 border 조정
> [시간표] 시간표 2차 스프린트 이슈 해결 (강의 정보, 타임테이블)

- src/pages/TimetablePage/MobilePage/MobilePage.module.scss
- src/pages/TimetablePage/MobilePage/index.tsx
- src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
- Close #250 
- 기능 : 시간표 이미지 하단 여백 제거
- issue : #250 
- 시간표 이미지 저장 시 하단에 생기는 여백을 제거했습니다.
- 웹
- 모바일
> [시간표]시간표 이미지 하단 여백 제거

- package.json
- src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss
젠킨스 빌드과정에서 autoprefixer의 warning을 에러로 치는문제를 수정합니다.
관련 쓰레드 https://bcsdlab.slack.com/archives/C06PLQTRZDE/p1716044609812629
> build: 빌드과정에서 CI=true로 변경되는 문제 수정

- src/pages/Store/StoreDetailPage/index.tsx
- src/pages/Store/StorePage/index.tsx
- 기능 : 로그 에러 수정
- issue : #
- 주변 상점 스크롤 로그의 이벤트 Title 틀린 스펠링 수정
- 주변 상점 검색창 포커스 시 카테고리가 하나 씩 밀리는 에러 수정
> [상점] 로그 에러 수정

- src/components/common/Header/hooks/useCheckPassword.ts
비밀번호 확인 시 api따라 반환 에러 코드를 401로 받던 것을 400으로 수정했습니다.
> [hotfix] 에러 상태 코드 수정

- src/pages/Auth/SignupPage/index.tsx
- 기능 : 회원가입 시 이메일 전체를 적는 경우 에러 분기 처리 
- `bcsd1234@gmail.com` 처럼 뒤에 이메일 형식이 붙는 경우 `이메일의 아이디 부분만 입력해주세요` 라는 에러 메시지 추가하였습니다.
- 이메일 형식은 `@`로 구분하였습니다.
> [유저] 회원가입 시 이메일 전체를 적는 경우 에러 분기 처리

- src/components/TimetablePage/Timetable/Timetable.module.scss
- src/components/TimetablePage/Timetable/index.tsx
- src/pages/IndexPage/components/IndexTimetable/index.tsx
- src/static/timetable.ts
- Close #316 
- 기능 : 18시 이후 강의도 볼 수 있습니다.
- issue : #316 
- 18시까지만 보여주던 시간표를 18시 이후 강의도 보여질 수 있게 합니다.
- 강의를 추가하거나 강의 시간을 알기 위해 강의를 클릭할 시(검은색 테두리 표시) 강의 시간만큼 시간표가 늘어납니다.
https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/11fde8cc-f32c-46fc-b5fb-dd69582a76d9
> [시간표] 시간표 늘리기

- src/App.tsx
- src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
- src/pages/Timetable/components/LectureList/index.tsx
- src/pages/Timetable/components/MyLectureTimetable/index.tsx
- src/pages/Timetable/hooks/useTimetableInfoList.ts
- Close #331 
- 기능 : 
- issue : #331 
* 최초 로그인시 시간표 api를 불러오지 않아, 시간표가 보이지 않음
=> api를 부르는 쿼리키에 현재 semester만 요소를 가지고 있었음. semester의 경우 로그인을 하지 않아도 가지고 있던 속성으로 쿼리키가 동일하기에 호출하지 않던 것으로 파악
**`[해결]`**: 쿼리키 인자로 semester + authorization로 설정하여 로그인을 하여 인증 토큰이 생겼을 경우 timetable api를 다시 호출하게 함.
* 시간표 편집 페이지 새로고침 시 강의 목록 사라짐
=> semester를 zustand를 사용해 전역적으로 사용하는 중, 시간표 메인 페이지 -> 편집 페이지로 이동할 때는 semester가 정상적을 store(저장)되지만 편지 상황에서 새로고침을 하면 semester 전역상태가 빈 문자열로 새로고침 되어 api 호출이 정상적으로 작동하지 않음
**`[해결]`**: url에 semester라는 params를 추가하여 store에 set하는 방식을 사용. 
`시간표 편집 페이지 새로고침 시 강의 목록 사라짐`를 해결하는 과정에서 url에 semester를 달아 해당 값으로 전역 상태 관리 set을 하는 방식을 사용했는데 더 괜찮은 방법이 있다면 코드리뷰 남겨주시면 감사하겠습니다. 현재로는 url방법 뿐이 생각이 나지 않았네요,,
> [시간표] 시간표 렌더링 및 시간표 수정시 강의 목록 렌더링 이슈 해결 

- src/components/common/Toast/TimetableToast/TimetableToast.module.scss
- src/components/common/Toast/TimetableToast/index.tsx
- src/components/common/Toast/useToast.tsx
- src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
- src/utils/hooks/useToastTimer.ts
- Close #330  
- 기능 : 시간표 공통 토스트
- issue : #330
- 시간표 공통 토스트를 만들었습니다.
- hover 시 시간이 멈추도록 했습니다.
- 되돌아가기 버튼에 대한 이벤트를 인자로 받도록 했습니다.
사용법은 다음과 같습니다.
``` ts
const toast = useToast();
toast.open({ message: '시간표 저장~', recoverMessage: '시간표 저장되었어요~', onRecover: () => console.log('언두') })
```
반드시 넣어야 하는 속성은 `message`, `recoverMessage`, `onRecover` 입니다.
https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74540646/057a78aa-0a3c-430d-b2c0-30fe423bf5d3
`시간표 저장` 버튼에 테스트로 넣어 놓았습니다! 머지할 때는 없앨 예정입니다.
> [시간표] 시간표 공통 토스트

- src/api/timetable/APIDetail.ts
- src/api/timetable/entity.ts
- src/api/timetable/index.ts
- src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
- src/pages/Timetable/components/CustomLecture/index.tsx
- src/pages/Timetable/hooks/useTimetableV2InfoList.ts
- Close #373
- 기능 : 시간표 강의 정보관련 api 연결
- issue : #373 
시간표 강의 정보 관련 api를 추가했습니다. 
api 및 시간표 직접 수정 기능까지 이번 PR에서 다루려고 했으나, 
기능상으로 시간표의 프레임에 따른 시간표 UI 변경 기능을 먼저 수정해야 할 것 같아 api 만 추가 하였습니다. 
위의 기능 개발 후에 새로운 feature 로 이어 작업하도록 하겠습니다.
> feat: 시간표 강의 정보 api 연결

- src/components/TimetablePage/LectureTable/LectureTable.module.scss
- src/components/TimetablePage/LectureTable/index.tsx
- src/components/TimetablePage/Timetable/Timetable.module.scss
- src/components/TimetablePage/Timetable/index.tsx
- src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
- src/pages/Timetable/components/LectureList/index.tsx
- src/pages/Timetable/components/MyLectureTimetable/index.tsx
- src/utils/zustand/myTempLecture.ts
- Close #381 
- 기능 : 유저팀 QA로 나온 부분 반영했습니다.
- issue : #381 
- 키보드 방향키로 강의 이동 선택 가능하게
- 강의목록 바깥 클릭 시 시간표 미리보기에 테두리 삭제
- 시간표 미리보기 테두리를 강의목록 부분 외에 클릭 시 없어지게
- 검색 조건에 교수명, 코드 추가
- 시간표 미리보기: 호버 -> 클릭, 시간표에 강의 추가: 클릭 -> 더블클릭
- 같은 강의인데 다른 시간인 강의를 시간표 미리보기에 테두리로 표시
- 방향키로 강의 이동 및 추가(Enter)
https://github.com/user-attachments/assets/b91606f2-84df-4de9-a518-5f78267f9dfa
- 검색 조건 추가
https://github.com/user-attachments/assets/e2976479-1444-4cfa-ad69-df68268f45ab
> [시간표] 유저팀 QA 반영

- src/components/TimetablePage/Listbox/index.tsx
- src/components/common/Header/MobileHeader/Panel/index.tsx
- src/components/common/Header/MobileHeader/index.tsx
- src/pages/TimetablePage/DefaultPage/index.tsx
- src/pages/TimetablePage/MobilePage/index.tsx
- src/pages/TimetablePage/components/Curriculum.tsx
- src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
- src/pages/TimetablePage/index.tsx
- src/utils/hooks/analytics/useLogger.ts
- Close #424 
- 기능 : 로깅 관련 수정 사항 수정하고, 뒤로가기 로그 추가했습니다.
추가로 `actionEventClick`의 `category`가 `button`인 부분을 `click`으로 수정했습니다.
- issue : #424 
- 브라우저 내장 뒤로가기 버튼 클릭 시 로그 추가
- 웹에서 스와이프를 통한 뒤로가기 시 로그 추가
- 뒤로가기 클릭 시
https://github.com/user-attachments/assets/3b7fae1e-d829-4181-8881-ad4989470662
- 스와이프로 뒤로가기 시
https://github.com/user-attachments/assets/219baeb7-fd34-4d39-af65-7842f1d5adf7
페이지 이동 후 페이지 아무 곳 클릭하면 정상 작동함.
- 비정상 작동 화면
https://github.com/user-attachments/assets/e18097ad-1ae3-4a02-930f-cb9f76c7eb19
- 정상 작동 화면(페이지 한 번 클릭 후 뒤로가기)
https://github.com/user-attachments/assets/935fce23-07d3-43d4-ac58-88f8794e0231
> [유저] 유저팀 로깅 수정, 공통 로그 수정

- src/pages/Store/StorePage/index.tsx
- src/utils/hooks/analytics/useLogger.ts
기존에는 필터, 정렬 버튼을 누를때마다 로깅되었는데, 토글 on될때마다 로깅되도록 수정했습니다 (da 요청사항)
> [비즈니스] 리뷰 필터버튼이 on 될때만 로깅되도록 수정

- src/pages/Timetable/components/SemesterList/AddSemesterModal/index.tsx
- src/pages/Timetable/hooks/useAddSemester.ts
- Close #460 
- 기능 : 아직 존재하지 않는 학기 에러 핸들링
- issue : #460 
[ 아직 존재하지 않는 학기 추가시 에러 ex)2024 겨울]
[토스트 추가]
> [시간표] 아직 존재하지 않는 학기 에러 핸들링

- src/index.tsx
- Close #468
- 기능 : queryClient의 default값으로 설정해둔 staleTime을 제거합니다.
- issue : #468
staleTime을 제거합니다. 과거의 제가 잘못 생각했던 부분을 바로잡습니다.
해당 내용은 BCSD_BLOG에 정리해두었습니다. ([링크](https://blog.bcsdlab.com/front-end/react/react-query))
의도치않은 사이드이펙트가 있을 수 있어, 팀별 기능들을 한번씩은 눌러봐야 하는 소요가 있습니다.
> [공통] staleTime 제거

- src/components/common/Modal/AlertModal/index.tsx
- Close #491 
- 기능 :  스크롤바 삭제로 인한 화면 움직임을 없앴습니다.
- issue : #491 
body에 `overflow: hidden`을 미적용
> [시간표] 학기 삭제 시 모달 생성과 함께 화면 움직임

- src/pages/Store/StoreDetailPage/index.tsx
- Close #504 
- 기능 : api 병럴 처리
- issue : #504 
한 컴포넌트 내에서 useSuspenseQuery가 여러 번 호출되면서 waterfall 현상이 일어나고 있었습니다.
promise.all을 통해 호출을 병렬처리 해줌으로써 위 현상을 막고 더 빠른 응답을 기대할 수 있습니다.
queryClient를 이용해서 tanstack query의 캐시 능력을 충분히 사용할 수 있도록 코드를 작성했습니다.
기존 네트워크 요청
변경된 네트워크 요청
> [비즈니스] 상점 상세 페이지 waterfall 현상 막기

- src/pages/TimetablePage/components/LectureList/index.tsx
- src/pages/TimetablePage/components/Timetable/index.tsx
- Close #502 
- 기능 : 비로그인 시 중복 시간표 토스트에러 문구 수정
- issue : #502 
기존의 qa 요소 중 하나였던, 커스텀 시간표에서 분반이 없을 때, 생기는 띄어쓰기를 삭제하였습니다.
* `분반 + 교수명 ` + 부분에 띄어쓰기가 하나 들어가 있어 나타나는 문제였습니다. 따라서 해당 공백을 삭제하고 템플릿 문자열 교수명 앞에 공백을 추가하는 방식으로 수정하였습니다.
* 중복 시간표 토스트 에러 문구 수정
* 비로그인 시 중복 시간표를 넣을 때 에러 문구 가 null로 떴습니다. 이는 로그인을 하지 않았을 때 받아오는 api res의 타입이 달라서 그런 것으로 파악하였습니다. 
*  토스트 에러에서는 모두 `alreadySelectedLecture.class_title`로 에러문구를 나타내고 있었지만, 로그인을 하지 않았을 경우에는 해당 정보가 `alreadySelectedLecture.name`에 들어있는 것으로 확인하여 에러 문구를 표시하는 분기에서 다르게 표현하였습니다.
* 또한, 커스텀 시간표로 시간표를 넣었을 경우에는 분반이 존재하지 않아 에러 문구를 표시할때 분반을 제거하는 분기를 하나 만들었습니다.
> [시간표] 비로그인 시 중복 시간표 토스트에러 문구 수정

- src/pages/TimetablePage/hooks/useTimetableDayListV2.ts
- Close #515 
- 기능 :  시간표에 시간이 잘못 나오지 않게 했습니다.
- issue : #515 
- 기존에 시간표에 강의가 9 to 6로 시간이 표시되었는데(_이슈 참고_) 로직이 잘못되어 있어 수정했습니다.
> [시간표] 시간표에 시간 잘못 나오는 이슈 해결

- src/api/timetable/entity.ts
- src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
- src/pages/TimetablePage/components/TimetableList/index.tsx
- src/pages/TimetablePage/hooks/useUpdateTimetableFrame.ts
삭제된 시간표 id에서 머무르는 현상을 수정했습니다.
현재 시간표가 삭제될 시 메인 시간표로 변경됩니다.
> [버그수정] 시간표 삭제 이후 기존 프레임 id에 머무르는 현상 수정

- src/components/TimetablePage/LectureTable/LectureTable.module.scss
- src/components/TimetablePage/LectureTable/index.tsx
- src/pages/TimetablePage/components/LectureList/LectureList.module.scss
- src/pages/TimetablePage/components/LectureList/index.tsx
- Close #518 
- 기능 : 빈 강의 목록(계절학기 등)과 시간표에 담은 강의가 없을 시 문구를 추가합니다.
- issue : #518 
**코드 이동으로 추가 코드가 많은 만큼 삭제 코드도 많습니다. 변경한 내용은 별로 없습니다!** 
- 코드 길이를 줄이고자 시간표 테이블 헤더(코드, 과목명, 분반 등..) 코드 위치를 변경했습니다.
- 강의 목록이 비어 있을 시, 내 시간표에 강의가 없을 시 안내 문구를 보여줍니다.
-빈 강의 목록
- 시간표에 추가한 과목이 없을 시
> [시간표] 빈 강의 목록에 대한 문구 추가

- src/pages/Auth/ModifyInfoPage/index.tsx
- Close #523 
- 기능 :  정보 수정 페이지 이동 시 회원의 기존 학과 정보를 불러옵니다.
- issue : #523 
- 회원의 학과 정보를 불러오지 않았던 코드 문제를 해결했습니다.(이전에 revert하면서 생긴 이슈인 것 같습니다.)
> [hotfix] 회원 학과 정보 불러오기

- src/pages/TimetablePage/components/CustomLecture/CustomLecture.module.scss
- src/pages/TimetablePage/components/CustomLecture/index.tsx
- Close #525 
- 기능 : 직접 추가 페이지에서 시간 및 장소 컴포넌트의 삭제 기능을 추가했습니다.
- issue : #525 
- 첫 '시간 및 장소' 박스는 삭제할 수 없게 X버튼이 안 보이게 했습니다.
- 그 외 추가된 '시간 및 장소' 박스에는 삭제 가능한 X버튼을 추가했습니다.
> [시간표] 시간 및 장소 삭제 기능 추가

- src/api/timetable/APIDetail.ts
- src/api/timetable/entity.ts
- src/api/timetable/index.ts
- src/pages/TimetablePage/hooks/useDeleteSemester.ts
- Close #530 
- 기능 : 학기 삭제 api 연동
- issue : #530 
- 기존에는 시간표 프레임을 삭제하는 api를 이용해서 그 학기에 있는 모든 시간표 프레임을 삭제해서 학기 삭제를 구현했는데 백엔에서 모든 시간표 프레임을 삭제하는 api를 만들어 주셔서 그것을 이용하여 학기 삭제를 구현했습니다.
> [시간표] 학기 삭제 api 연동

- src/pages/TimetablePage/components/SemesterList/index.tsx
- Close #533
- 기능 :  잘못된 useEffect 사용이 있었습니다. 삭제했습니다.
- issue : #533 
잘못된 useEffect 사용이 있었습니다. 삭제했습니다.
급하게 이슈 수정하느라 코드 신경을 많이많이많이 안 썼습니다..
다음부터 신경 많이 쓰고 반영하겠습니다.
> [hotfix] 학기 설정 오류 수정

- .gitignore
- vite.config.ts
- Close #553
- yarn build했을 때 Vite는 기본적으로 /dist폴더를 생성하지만, 기존처럼 /build폴더에 build산출물을 만들도록 수정했습니다.
> Vite 마이그레이션 빌드 폴더 수정

- src/components/common/Footer/index.tsx
- src/components/common/Header/MobileHeader/Panel/index.tsx
- src/components/common/Header/PCHeader/index.tsx
- Close #559
- 기능 : 교내 시설물 정보 로깅
- issue : #559
- 교내 시설물 정보 진입점 헤더, 푸터, 햄버거에 로깅을 추가했습니다.
- 교내 시설물 정보 로깅의 경우 급하게 추가할 필요가 있어 핫픽스로 추가합니다.
> [캠퍼스] 교내 시설물 정보 로깅 추가

- src/pages/Auth/ModifyInfoPage/index.tsx
- Close #561 
- 기능 :  닉네임을 필수가 아닌 선택이 되게 했습니다.
- issue : #561 
- 매우 큰 이슈는 아니라 급한 PR은 아닙니다.
1. 이번 이슈를 해결하면서 또다른 이슈를 발견하여 수정했습니다.
**닉네임을 수정하고 중복 검사를 안 했지만 그대로 수정 완료가 되어 인덱스 페이지로 넘어가는 현상**을 발견했습니다. 물론 닉네임은 수정이 되지 않았습니다. 로직을 봤을 때는 닉네임을 수정하고 중복확인을 하지 않은 채 수정 완료를 누르면 '닉네임 중복확인을 해주세요' 토스트가 뜨는 게 정상으로 보였습니다. 하지만 `useImperativeHandle`의 사용과 동시에 ref로 input값을 받고 있어 수정완료를 누를 때 이전값을 참조하고 있어서 **`ref`대신 `nickname state`을 추가**했습니다.
2. 닉네임을 필수가 아닌 선택으로
`nicknameElementRef.current?.value !== userInfo?.nickname`
닉네임을 작성하지 않고 회원가입을 한 사용자는 `userInfo.nickname` 값이 `null`이 됩니다.
그리고 input에서 아무런 값을 입력하지 않은 초기값은 빈 문자열(`''`)이 됩니다. 따라서 위 로직의 결과값은 true가 됩니다.
저희가 원하는 결과는 닉네임을 수정 또는 추가하지 않고 정보수정을 성공적으로 마치는 것입니다. 하지만 위와 같은 경우에서는 `'' !== null` 의 결과가 true가 되기 때문에 `닉네임 중복확인을 해주세요.`토스트와 함께 정보수정을 마칠 수 없게 됩니다.
단지 **빈 값에 대해 빈 …
> [hotfix] 정보수정에서 닉네임이 필수값이 되어버리는 이슈

- src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
- src/pages/IndexPage/components/IndexStore/index.tsx
- src/pages/Store/StorePage/StorePage.module.scss
- src/pages/Store/StorePage/index.tsx
카테고리 개수가 2개 늘어남에 따라 UI가 깨진 현상을 수정했습니다.
카테고리는 현재 스프린트 기획상 12개만 보여줍니다.
> [비즈니스] 카테고리 추가에 따른 UI 대응

- src/api/timetable/entity.ts
- src/components/Cafeteria/CafeteriaInfo/index.tsx
- src/pages/TimetablePage/hooks/useTimetableV2Mutation.ts
- Close #579 
- 기능 : 정규 강의 추가 api(POST/v2/timetables/lecture)의 요청값 중 `classTitle`, `classTime`, `professor`을 `null`로, `grades`를 `'0'`으로 수정했습니다.
- issue : #579 
백엔드 측에서 커스텀 강의와 정규 강의 구분을 위해 요청값에 null을 넣어달라는 요청으로 정규 강의 추가 api(POST/v2/timetables/lecture)의 요청값 중 `classTitle`, `classTime`, `professor`을 `null`로, `grades`를 `'0'`으로 수정했습니다.
> [시간표] 강의 추가 api 요청값 수정

- src/pages/Store/StorePage/components/SearchBarModal/index.tsx
- src/pages/Store/StorePage/index.tsx
- QA에서 정상적으로 동작하지 않은 부분 수정하였습니다.
- SuspenseQuery를 적용하며 함수쪽에서 depth가 2개 이상인 경우에는 undefined로 에러로 인해 페이지가 중단되는 현상을 수정하였습니다.
- 모바일 화면에서 역정렬 기능을 전부 제거하였습니다.
- 검색 시 autocomplete 기능을 제거하였습니다.
- A/B 테스트를 위한 기능은 전체적으로 완료되어 stage 테스트 이후 배포하면 될 것 같습니다.
- 추가적인 키보드 UI 수정은 목요일 이내로 작업하겠습니다.
- 추가적으로 궁금한 점은 컴퓨터에서 엔터키를 눌렀을 때 가장 첫번째에 있는 페이지나 라우팅을 해야하는 기능을 넣어야 하나요?
- 모바일 역정렬 기능 제거
- 검색 시 상점 이동 기능
https://github.com/user-attachments/assets/7ad3dae0-c8e7-4ec0-ab87-ccd06d0ed848
> [QA] 검색 시 카테고리 선택 불가 에러와 정렬 기능 제거

- src/pages/Auth/ModifyInfoPage/index.tsx
- src/pages/Auth/SignupPage/index.tsx
- Close #588 
- 기능 : 학번을 선택하지 않은 채 학부를 선택하면 반영되지 않는 이슈를 해결했습니다.
- issue : #588 
- 학번이 빈 문자열일 시 학부와 함께 빈 값을 반환하는 경우를 없앴습니다.
> [유저] 학부를 선택해도 반영되지 않는 이슈

- src/components/common/IntroToolTip/index.tsx
- src/pages/Store/StorePage/index.tsx
모바일 툴팁을 닫은 후에도 새로고침 시 계속 팝업되는 오류 수정
- 기능 : 모바일 화면 툴팁 계속 뜨는 오류 수정
- issue : #
모바일 팝업을 띄우는 state가 isTooltipOpen,과 isToolTipOpen 두개가 있어 발생한 문제를 해결했습니다.
> [주변상점] 모바일 툴팁 오류 수정

- src/components/common/Header/MobileHeader/Panel/index.tsx
- src/pages/Auth/ModifyInfoPage/hooks/useUserInfoUpdate.ts
- src/pages/Auth/ModifyInfoPage/index.tsx
- src/pages/Auth/SignupPage/hooks/useNicknameCheckServer.ts
- src/static/category.ts
- Close #596 
- 기능 : 사이드 내비바 UI 수정, 닉네임 제거 가능하게 수정
- issue : #596 
- 사이드 내비바에서 닉네임과 이름이 모두 없는 경우 "`님, 안녕하세요!`"라고 표시되던 것을 "`회원님, 안녕하세요!`"로 수정했습니다. 닉네임이 있는 경우는 닉네임이, 닉네임이 없고, 이름이 있는 경우는 이름이 표시되도록 수정했습니다.
- 정보 수정에서 submit 시 409에러를 반환하는 경우가 이미 존재하는 닉네임이 있을 때 반환하는 경우여서 에러 메시지를 수정했습니다.
- `코인 for business`로 되어 있던 것을 `코인 사장님`으로 수정했습니다. (헤더, 푸터, 사이드내브바 모두 반영)
- 닉네임이 기존에 있는 사용자의 경우, 닉네임을 제거하기 위해 빈 문자열로 남기고 제출 시 닉네임 input에 변동이 있었기 때문에 중복확인을 요합니다. 하지만 빈 문자열로 중복확인을 했을 때는 닉네임을 입력하라고 합니다. 이를 막기 위해 닉네임을 빈 문자열로 제출 시 중복확인을 요하지 않고 제출이 가능하게 수정했습니다.
- 닉네임, 이름 모두 없는 경우
> [유저] 모바일웹 사이드 내비바 UI 수정

- src/pages/Auth/SignupPage/index.tsx
- Close #609 
- 기능 : 회원가입 페이지에서 성별 선택이 안 되는 것을 수정
- issue : #609
- 성별 선택 드롭다운에 `onBlur` 이벤트를 추가하여 바깥 클릭 시 드롭다운이 닫히도록 구현했었습니다. 그 상태로 성별 선택을 위해 `li` 아이템에 `onClick` 이벤트를 실행하려 하니 성별 선택이 되지 않은 채로 드롭다운 메뉴가 닫히는 현상이 발생했습니다. 그 이유가 이벤트 핸들러의 작동 순서 때문이라는 것을 알게되었습니다.
`onBlur -> onClick` 순으로 이벤트 핸들러가 작동하기 때문에 `onClick` 이벤트가 실행되지 않고 드롭다운이 닫히는 것이었습니다! 따라서 `onBlur`의 작동 순서보다 앞서는 `onMouseDown` 이벤트를 사용해 해결했습니다.
> [유저] 회원가입 페이지 성별 선택 불가 이슈 해결

- src/components/TimetablePage/LectureTable/index.tsx
- src/pages/TimetablePage/ModifyTimetablePage/index.tsx
- src/pages/TimetablePage/components/CustomLecture/index.tsx
- src/pages/TimetablePage/components/LectureList/index.tsx
- Close #615 
- 기능 : 계절학기 시 강의 수정 페이지 안 들어가지는 오류 수정
- issue : #615 
- 학기가 계절학기인 경우 강의 수정 페이지가 안 들어가지는 오류를 수정했습니다.
- 또한 내 강의정보(`myLectures`)가 `undefined`인 경우가 있어 이 경우 일부 `Array` 메서드를 사용하지 못하므로 조건 처리했습니다.
> [hotfix, 시간표] 계절학기 시 강의 수정 페이지 안 들어가지는 오류 수정

- src/pages/Bus/BusRoutePage/components/TimeDetail/TimeDetailPC/TimeDetailPC.module.scss
- Close #648 
- 기능 : 폰트 깨짐으로 인해 버튼 내부에서 줄바꿈이 일어나는 버그입니다.
- issue : #648 
버튼에서 `width` 속성을 제거하였습니다.
> [hotfix] 지금 출발 버튼 크기 수정

- src/pages/Auth/SignupPage/index.tsx
- Close #659 
- 기능 : 회원가입 로깅 추가
- issue : #659 
기존에는 `회원가입 완료` 로깅이 회원가입 버튼 클릭 시점에 실행되어, 회원가입이 실패해도 `회원가입 완료` 로그가 전달되는 문제가 있었습니다. 이를 해결하기 위해 로깅 위치를 회원가입 성공 시점으로 수정하였습니다.
또한, 성별 및 학부 관련 로깅을 추가하였습니다.
> [유저] 회원가입 로깅 추가 

- src/api/timetable/APIDetail.ts
- src/components/TimetablePage/LectureTable/index.tsx
- src/components/TimetablePage/Listbox/index.tsx
- src/pages/IndexPage/components/IndexTimetable/index.tsx
- src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
- src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
- src/pages/TimetablePage/MainTimetablePage/index.tsx
- src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
- src/pages/TimetablePage/ModifyTimetablePage/index.tsx
- src/pages/TimetablePage/components/CustomLecture/index.tsx
- src/pages/TimetablePage/components/LectureList/index.tsx
- src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
- src/pages/TimetablePage/components/MainTimetable/index.tsx
- src/pages/TimetablePage/components/Timetable/Timetable.module.scss
- src/pages/TimetablePage/components/Timetable/index.tsx
- src/pages/TimetablePage/hooks/useEditTimetableLectureCustom.ts
- src/pages/TimetablePage/hooks/useEditTimetableLectureRegular.ts
- src/pages/TimetablePage/hooks/useMyLectures.ts
- src/pages/TimetablePage/hooks/useRollbackLecture.ts
- src/pages/TimetablePage/hooks/useRollbackTimetableFrame.ts
- src/pages/TimetablePage/hooks/useTimetableMutation.ts
- src/static/timetable.ts
- src/utils/zustand/myCustomTempLecture.ts
- Close #650 
- 기능 : 커스텀 시간표 페이지를 리팩터링했습니다.
- issue : #650 
@ChoiWonBeen 님의 피드백을 받고 정리한 [관련 노션](https://chatter-afternoon-e41.notion.site/CustomLecture-646643b63d78448c88130e4febb2c690)입니다.
[관련 스레드](https://bcsdlab.slack.com/archives/CGQM7A3S8/p1738594121084649)입니다.
아무래도 **노션에서 정리한 5번**과 **6번**을 중점적으로 리뷰해주시면 될 것 같습니다.
**5번 내용**은 지금까지 `CustomLecture`라는 폼 컨테이너에 모든 state를 넣고 관리했는데 시간과 장소를 묶는 컨테이너를 컴포넌트화할 필요가 있다하여 `TimeSpaceInput`이라는 이름으로 컴포넌트화했습니다.
~~**6번 내용**은 useEffect를 줄일 수 있으면 줄여라 였는데, 결과적으로는 더 늘리는 꼴이 되었습니다. 그 이유는 아래와 같습니다.
customTempLecture라는 현재 커스텀 일정의 정보를 담고 있는 객체를 전역 상태로 관리하고 있습니다. 이 객체가 하는 역할은 그 강의 정보를 시간표에 미리보기볼 수 있도록 하는 것입니다. 따라서 form을 업데이트 할 때마다 customTempLecture도 즉각 업데이트를 해줘야 하는데, 컴포넌트를 분리하다 보니 자식, 부모, 컴포넌트에서 updateCustomLecture를 해야 하는 상황이 있었습니다. 
**"한 줄 요약"**
컴포넌트화해서~~ -> …
> [시간표] 커스텀 시간표 페이지 리팩터링

- src/pages/Articles/LostItemDetailPage/LostItemDetailPage.module.scss
- src/pages/Articles/LostItemDetailPage/index.tsx
- src/pages/Articles/LostItemWritePage/components/FormCategory/index.tsx
- src/pages/Articles/LostItemWritePage/components/FormDate/index.tsx
- src/pages/Articles/LostItemWritePage/components/LostItemForm/index.tsx
- src/pages/Articles/LostItemWritePage/index.tsx
- src/pages/Articles/hooks/useArticlesLogger.ts
- Close #676
- 기능 : 분실물 QA 이슈 수정
- issue : #676 
* 분실물 또는 습득물이 0개일 때 작성 완료 버튼을 누르면 에러가 발생하던 현상을 수정했습니다.
* 총학생회 이외의 사람이 작성한 글에서 분실물 수령 문구가 뜨는 현상을 수정했습니다.
* 삭제 버튼을 디자인과 동일하게 우측 정렬로 수정했습니다.
분실물 또는 습득물이 0개일 때는 api를 호출하지 않고 토스트 메시지를 띄웁니다.  
<br><img width="644" alt="image" src="https://github.com/user-attachments/assets/0e85d872-5574-4749-87c8-442763ad7abb" />
<br>총학생회 이외의 사람이 작성한 글에서 분실물 수령 문구가 뜨지 않습니다.
<br><img width="641" alt="image" src="https://github.com/user-attachments/assets/bbcd306d-0406-4710-b9c2-71bec0165fce" />
<br> 삭제 버튼이 우측 정렬 되었습니다.<br>
> [캠퍼스] 분실물 QA 수정

- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/api/auth/index.ts
- src/api/graduationCalculator/index.ts
- src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
- src/pages/GraduationCalculatorPage/hooks/useAgreeGraduationCreidts.ts
- src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
- src/pages/GraduationCalculatorPage/index.tsx
- Close #679 
- 기능 :  학적 정보 수정 api를 추가했습니다.
- issue : #679 
- 기존 정보 수정 api 대신 세부 전공이 추가된 학적 정보 수정 api를 추가했습니다.
- 졸업학점 계산 동의 api를 졸업학점 계산기 페이지 최초 이동 시에만 호출하는 것으로 변경했습니다.
> [졸업학점계산기] 학적 정보 수정 추가

- src/pages/Articles/LostItemDetailPage/components/ReportModal/index.tsx
- src/pages/Articles/LostItemDetailPage/index.tsx
- src/pages/Articles/LostItemWritePage/components/FormCategory/index.tsx
- src/pages/Articles/LostItemWritePage/components/LostItemForm/index.tsx
- src/pages/Articles/LostItemWritePage/index.tsx
- src/pages/Articles/components/LostItemRouteButton/index.tsx
- src/pages/Articles/hooks/useArticlesLogger.ts
- Close #691 
- 기능 : 분실물 로깅 수정입니다.
- issue : #691 
분실물 로깅이 추가, 수정되었습니다.
* 추가: 주인을 찾아요, 잃어버렸어요, 신고, 신고하기 버튼에 대한 로깅
* 수정: 습득물 페이지 로깅
* 주인을 찾아요(습득물 글쓰기), 잃어버렸어요(분실물 글쓰기) 버튼의 로깅을 추가하였습니다.
* 신고와 신고하기 버튼의 로깅을 추가하였습니다.
* 습득물 페이지에 분실물 로깅이 들어가 있던 현상을 수정하였습니다.
> [캠퍼스] 분실물 로깅 수정

- src/pages/TimetablePage/components/CustomLecture/index.tsx
- Close #693 
- 기능 : 드롭다운 메뉴 위로 올라가는 이슈를 수정합니다.
- issue : #693 
- 시간, 장소 컴포넌트가 하나인 경우 reverse가 되지 않도록 조정했습니다.
- 또한, 시간,장소 컴포넌트 삭제 시 `handleScroll()`을 하여 botton position을 변경해야 하는데 컴포넌트 추가 시에만 `handleScroll()`을 호출하던 것을 수정했습니다.
> [커스텀시간표] 드롭다운 메뉴 위로 올라가는 이슈 수정

- src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
- src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
- src/pages/GraduationCalculatorPage/hooks/useGeneralEducation.ts
- src/pages/TimetablePage/hooks/useDeleteTimetableLecture.ts
- Close #699 
- 기능 : 컴포넌트 높이를 고정하여 배치를 조정합니다.
- issue : #699 
- 교양 영역이 두 줄일 경우와 세 줄일 경우 컴포넌트 높이가 동일합니다.
- queryKey를 추가하여 새로고침 없이 값이 바로 반영되도록 합니다.
> [졸업학점계산기] 컴포넌트 높이 수정 및 queryKey 추가

- src/pages/Articles/components/ArticleContent/ArticleContent.module.scss
- src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
- Close #709 
- 기능 : 회원가입, 정보수정 페이지에서 닉네임 중복확인 시 영문, 한글, 숫자 외 입력 불가 조건을 추가했습니다.
- issue : #709 
- 회원가입, 정보수정 페이지에서 닉네임 중복확인 시 영문, 한글, 숫자 외 입력 불가 조건을 추가했습니다.
> [hotfix, 유저] 닉네임 중복확인 조건 추가

- src/pages/Auth/ModifyInfoPage/index.tsx
- Close #721 
- 기능 : 성별이 있는지 없는지를 구분하여 요청값을 보냅니다.
- issue : #721 
- 성별이 있는지 없는지를 구분하여 요청값을 보냅니다.
> [유저] 정보 수정 시 성별 미선택하면 "null"로 요청값 보내는 이슈 해결

- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/api/auth/index.ts
- src/api/graduationCalculator/entity.ts
- src/pages/GraduationCalculatorPage/CalculatorHelpModal/CalculatorHelpModal.module.scss
- src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
- src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
- src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
- src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss
- src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
- src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
- src/pages/GraduationCalculatorPage/components/StudentForm/StudentForm.module.scss
- src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
- src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
- src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss
- src/pages/TimetablePage/hooks/useAllMyLectures.ts
- src/utils/hooks/state/useUserAcademicInfo.ts
- Close #720 
- 기능 : 졸업학점계산기 기능 2차 qa 이슈를 수정했습니다.
- issue : #720 
- 기존 `useUser` 훅으로 사용자 정보를 받아왔는데, `useUserAcademicInfo`라는 훅을 새로 만들어 졸학계 쪽에만 대체했습니다.
두 훅의 차이점으로 `useUser`는 **major**로 학부(예: 전기전자통신공학부)를 받고 있고, `useUserAcademicInfo`는 **department**로 학부(예: 전기전자통신공학부)를 **major**로 전공(예: 전기공학전공)을 받고 있습니다.
- `Pretendard` 폰트 설치되어 있지 않아 `sans-serif`로 적용되어 글자가 깨지는 경우를 대비하여 해당 텍스트가 줄바꿈되지 않도록 했습니다.
- 툴팁들의 너비를 고정시켰습니다.
- 학기 강의 개설 목록을 조회할 때 수강한 강의만을 조회 시 학기와 상관없이 전체 강의를 조회할 수 있도록 수정했습니다.
> [졸업학점계산기] 2차 qa 이슈 수정

- src/pages/Bus/BusRoutePage/components/SelectDropdown/SelectDropdown.module.scss
- src/pages/Bus/BusRoutePage/components/SelectDropdown/index.tsx
- Close #726
- 기능 : 
- issue : #
끝 옵션일 경우 조정하는 버튼에 after에서 요소를 만듦으로써 버튼을 가렸는데 이때 버튼이 동작하는 이슈가 있었습니다.
끝 옵션을 경우 버튼을 span 요소로 대체하는 식으로 해결했습니다.
> [fix] 버스 날짜/시간 선택 버튼 비활성화 시 보이는 문제 수정

- src/api/coopshop/APIDetail.ts
- src/pages/Cafeteria/hooks/useCoopshopCafeteria.ts
- Close #732 
- 기능 : 
- issue : #732
COOPSHOP_IDS 번호가 잘못 들어가서 학식당이 아닌 우편취급국 시간이 보이던 문제를 해결했습니다.
> [hotfix] 식당 운영 시간이 아닌 잘못된 값 보이는 문제 수정

- src/components/common/Footer/Footer.module.scss
- src/components/common/Footer/index.tsx
- Close #748 
- 기능 : 문의하기 진입점 추가
- issue : #748 
- 푸터에 문의하기 버튼을 추가했습니다.
- 웹
- 모바일웹
> [hotfix] 웹 문의하기 버튼 추가

- src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
- Close #756 
- 기능 : 가게 이미지의 비율을 그대로 살리고 뒤에 배경을 둠
- issue : #756
가게 이미지의 비율을 그대로 살리고 뒤에 배경을 둠
> [비지니스] 가게 이미지 리사이징 이슈 해결

- src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
- Close #758
- 기능 : 모바일 시간표 학기 드롭다운 버튼 배경 active 에러 해결
- issue : #758
- 모바일 환경과 데스크톱 환경에서 `미디어 쿼리`를 나눠서 구현
`hover` 여부를 기준으로 나누어 데스크톱에 `hover` 가상 클래스를 따로 추가
> [hotfix] 모바일 시간표 학기 드롭다운 버튼 배경색 active 에러

- src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss
- src/pages/TimetablePage/components/MainTimetable/MyLectureTimetable.module.scss
- src/pages/TimetablePage/components/TotalGrades/TotalGrades.module.scss
- Close #779 
- 기능 : 글꼴 누락으로 인한 레이아웃 깨짐 현상을 수정하였습니다.
- issue : #779 
상단 버튼들의 글꼴 크기를 1px씩 줄였습니다.
Pretendard 글꼴을 해지하였을 때도 레이아웃이 일정하게 유지됩니다.
> refactor: 폰트 크기 수정

- src/pages/Store/StorePage/components/SearchBar/index.tsx
- src/pages/Store/StorePage/components/SearchBarModal/index.tsx
- src/pages/Store/StorePage/index.tsx
- Close #816 
- 기능 : 검색창 무한 엔터로 인한 무한 검색 방지
- issue : #816 
- onKeyDown으로 'Enter'키를 받고 있어서 'Enter'키를 꾹 누를 시 계속 onKeyDown 이벤트 핸들러가 호출되는 현상을 onKeyUp 이벤트 핸들러로 해결했습니다.
- 주변상점 **검색 완료 시** 상점에 대한 정보만 나타냈던 것을 검색어와 관련된 메뉴를 가진 상점도 나타내게 수정했습니다.(앱과 ux 일치)
- 모바일뷰에서 검색 완료 시 모달이 닫히지 않는 현상을 수정했습니다.
> [hotfix, 주변상점] 엔터 키 무한 입력으로 인한 무한 검색 이슈 해결

- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/api/auth/index.ts
- src/pages/Auth/SignupPage/Steps/CompleteStep/CompleteStep.module.scss
- src/pages/Auth/SignupPage/Steps/CompleteStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/MobileExternalDetailStep.module.scss
- src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/MobileStudentDetailStep.module.scss
- src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileUserTypeStep/MobileUserTypeStep.module.scss
- src/pages/Auth/SignupPage/Steps/MobileUserTypeStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileVerificationStep/MobileVerification.module.scss
- src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx
- src/pages/Auth/SignupPage/Steps/Verification/Verification.module.scss
- src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
- src/pages/Auth/SignupPage/components/CustomSelector/CustomSelector.module.scss
- src/pages/Auth/SignupPage/index.tsx
- src/static/auth.ts
- Close #819 
- 기능 : 회원가입 외부인 페이지 구현 및 api 변경사항 대응
- issue : #819 
- 회원가입 로직 중 외부인 회원가입 로직을 구현했습니다. 
- `/v2/user/general/register` , `/v2/user/student/register`, `/user/verification/sms/send`, `/user/verification/sms/verify` api 에 변경사항이 생겨 대응했습니다.
- 모바일 페이지만 구현 완료했습니다.
- 휴대전화 인증번호의 경우 slack 에서 `코인_이벤트알림_stage` 에서 확인 가능합니다.
- 아이디 입력 부분의 경우 변경된 디자인이 아직 나오지 않아 추가하지 않았습니다. 디자인이 추가된 후 이어서 PR 올리도록 하겠습니다. 
- 아이디 입력 부분이 구현되지 않아 회원가입 완료 또한 주석 처리해놨습니다.
> Feat/#819/update signup api UI

- src/pages/Store/StorePage/components/SearchBarModal/index.tsx
- Close #839 
- 기능 : 공백, 빈 문자열 시 연관 검색 api 미호출
- issue : #839 
- 공백 혹은 빈 문자열에 대해 연관 검색 api를 호출하지 않도록 했습니다.
> [hotfix, 주변상점] 빈 문자열, 공백 입력 시 api 미호출

- src/api/auth/APIDetail.ts
- src/api/auth/entity.ts
- src/api/auth/index.ts
- src/assets/svg/arrow-back.svg
- src/pages/Auth/SignupPage/Steps/CompleteStep/CompleteStep.module.scss
- src/pages/Auth/SignupPage/Steps/ExternalDetailStep/ExternalDetailStep.module.scss
- src/pages/Auth/SignupPage/Steps/ExternalDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/StudentDetailStep/StudentDetailStep.module.scss
- src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/VerificationStep/VerificationStep.module.scss
- src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
- src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
- src/pages/Auth/SignupPage/components/CustomInput/index.tsx
- src/pages/Auth/SignupPage/components/CustomSelector/CustomSelector.module.scss
- src/pages/Auth/SignupPage/components/CustomSelector/index.tsx
- src/pages/Auth/SignupPage/index.tsx
- src/static/auth.ts
- Close #843 
- 기능 : 회원가입 학생 정보기입 페이지 추가
- issue : #843 
학생 정보기입 페이지에 다음과 같은 기능이 추가되었습니다. (UI는 [지난 PR](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/827)에서 다루었습니다)
1. 아이디 중복 체크
2. 닉네임 중복 체크
3. 이메일 중복 체크
4. 학번 유효성 검사
5. 회원가입 완료
추가로 이메일 중복 체크는 '회원가입 완료' 버튼을 누를 때 진행됩니다.
중복된 이메일은 가입처리 되지 않고, 이미 존재하는 이메일이라는 경고 메시지를 띄웁니다.
https://github.com/user-attachments/assets/c2cab8ae-f895-438a-87f9-a4d2b16d10a9
> [유저] 학생 정보기입 페이지 기능 추가

- src/api/auth/entity.ts
- src/pages/Auth/SignupPage/Steps/ExternalDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx
- src/pages/Auth/SignupPage/Steps/Terms/index.tsx
- src/pages/Auth/SignupPage/Steps/VerificationStep/VerificationStep.module.scss
- src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
- src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
- src/pages/Auth/SignupPage/components/CustomInput/index.tsx
- src/pages/Auth/SignupPage/index.tsx
- Close #849 
- 기능 : api 필드 추가 및 에러 수정을 진행하였습니다.
- issue : #849 
* 학생 회원가입(문자 인증)과 일반인 회원가입(문자 인증)의 Request body에 추가된 필드를 수정하였습니다.
* 기존에 `useEffect`를 많이 사용하는 방식 대신, `react-form-hook`의 `onChange`를 활용하여 코드를 리팩토링하였습니다.
* 회의 때 진행한 임시 QA에서 나온 이슈를 해결하였습니다.
* input의 padding 조절
* 문자 인증 에러 메시지 위치 조절
https://github.com/user-attachments/assets/cd373180-4ee5-45b3-b3f2-c3b8118ea786
> [유저] 회원가입 api 필드 추가 및 에러 수정

- src/pages/Auth/AuthPage/Auth.module.scss
- src/pages/Auth/SignupPage/SignupPage.module.scss
- src/pages/Auth/SignupPage/Steps/MobileVerificationStep/MobileVerification.module.scss
- src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx
- src/pages/Auth/SignupPage/Steps/Terms/Terms.module.scss
- src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
- src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
- src/static/routes.ts
- 기능 : 회원가입 UI 에러 수정
- 전체 UI의 Layout margin, padding 변경
- 에러 메시지 별 다른 UI 적용
- 요청 횟수 초과 시 `로그인하기` 링크 삭제
- 이미 가입된 전화번호 일 때 `로그인하기` 링크와 `문의하기` 링크 및 문구 추가
https://github.com/user-attachments/assets/db29b63e-4029-40e5-8cab-3ec9700b8b97
> [유저] 회원가입 UI 에러 수정

- src/components/ui/Banner/Banner.module.scss
- src/components/ui/BannerB/BannerB.module.scss
- Close #853 
- 기능 : 배너 간격 조정
- issue : #853 
- '일주일 동안 그만 보기'와 '닫기'버튼 간격을 조정하였습니다.
(웹)
(모바일)
> [핫픽스] 배너 버튼 간격 조정

- src/api/auth/APIDetail.ts
- src/pages/Auth/FindIdPage/PC/ResultPage/index.tsx
- src/pages/Auth/FindPasswordPage/PC/PCResetPasswordPhone/PCResetPasswordPhone.module.scss
- src/pages/Auth/FindPasswordPage/PC/PCResetPasswordPhone/index.tsx
- src/pages/Auth/FindPasswordPage/PC/PCVerifyEmail/PCVerifyEmail.module.scss
- src/pages/Auth/FindPasswordPage/PC/PCVerifyEmail/index.tsx
- src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/PCVerifyPhone.module.scss
- src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/index.tsx
- src/utils/hooks/auth/useEmailVerification.ts
- Close #885 
- 기능 : 이메일로 비밀번호 찾는 플로우를 추가하였습니다.
- issue : #885 
이메일로 비밀번호를 찾는 플로우를 추가하였습니다.
제 개인 네이버 계정이기 때문에 테스트 계정을 제공해 드릴 수 없습니다...!
테스트는 아이디와 이메일이 등록되어 있는 계정으로만 가능합니다.
> [유저] 이메일로 비밀번호 찾기 페이지 추가

- src/pages/Club/ClubListPage/ClubListPage.module.scss
- 기능 : 모바일뷰 이미지 사이즈 조정
- issue : #
모바일뷰 이미지 사이즈를 조정했습니다.
> fix: 모바일뷰 이미지 사이즈 조정

- src/pages/Auth/FindPasswordPage/Mobile/MobileVerifyEmail/index.tsx
- src/pages/Auth/FindPasswordPage/Mobile/MobileVerifyPhone/index.tsx
- src/pages/Auth/FindPasswordPage/PC/PCVerifyEmail/index.tsx
- src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/index.tsx
- src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
- src/pages/Auth/SignupPage/components/PCCustomInput/index.tsx
- src/utils/hooks/auth/useEmailVerification.ts
- src/utils/hooks/auth/usePhoneVerification.ts
- Close #914 
- 기능 : 유저팀 QA 수정
- issue : #914 
* 아이디와 일치하지 않은 이메일로도 아이디/비번찾기 가능
* 한번 인증하면 이메일 칸이 잠겨서 옳은 이메일로 수정이 안되는 현상
* 인증 번호 전송 버튼에 pending 상태 추가
* 그 외, 중복 처리나 브랜치 최신화에 따른 코드 수정
**비밀번호 찾기- 휴대전화**
https://github.com/user-attachments/assets/48350cf8-ca87-43c1-b43a-c306c03add47
**비밀번호 찾기 - 이메일**
https://github.com/user-attachments/assets/50def7ed-1823-47b5-a3b2-abda670fe858
가입한 `아이디-전화번호`와 `아이디-이메일`가 일치하지 않게 입력하고 인증을 완료한 후, 다음 버튼을 눌렀을 때
잠겼던 입력창이 풀어지는 것을 확인하면 됩니다.
> [유저] QA 이슈 수정

- src/pages/Club/ClubEditPage/index.tsx
- src/pages/Club/ClubListPage/index.tsx
- src/pages/Club/NewClubPage/components/AdditionalInfoModal/index.tsx
- src/pages/Club/NewClubPage/components/MobileView/NewClubMobileView.module.scss
- src/pages/Club/NewClubPage/components/MobileView/index.tsx
- src/pages/Club/NewClubPage/components/PCView/NewClubPCView.module.scss
- src/pages/Club/NewClubPage/components/PCView/index.tsx
- Close #925
- 기능 : 동아리 생성 과정에서 오픈채팅 링크 작성 중 https:// 를 누락하는 경우가 발생하여 기본값으로 보여주도록 수정
- issue : #925
동아리 생성 과정에서 오픈채팅 링크 작성 중 https:// 를 누락하는 경우가 발생하여 기본값으로 보여주도록 수정
동아리 목록 조회 API에서 정렬 기본 param 변경된 부분 반영
https://github.com/user-attachments/assets/c9a79169-1685-4aac-aaf3-cc1657da1609
> [hotfix] 동아리 오픈채팅 링크 입력 방식 개선 (https:// 누락 방지)

- src/pages/Club/ClubDetailPage/index.tsx
- Close #975  
- 기능 : 오픈채팅 링크 길이 초과 방지를 위해 static하게 적용 및 말줄임표 처리
- issue : #975
> [hotfix] 동아리 오픈채팅 길이 초과 이슈

- src/pages/Bus/BusRoutePage/hooks/useCoopSemester.ts
- Close #988
- 기능 : useCoopSemester의 query key 네이밍을 변경했습니다.
- issue : #988
https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/982
위 작업에서 api에서 내려주는 학기 값을 이용하기 위해 useCoopSemester 훅을 만들었는데
이때 사용한 queryKey 값이 semester로 useSemesterOptionList 훅의 queryKey와 동일하여 버그가 발생하여 수정했습니다.
> [hotfix] 버스 페이지에서 메인 화면 이동 시 흰 화면 렌더링

- src/lib/gtag.ts
- src/pages/_app.tsx
- 기능 : next 로깅 방식에서 이전 로깅 방식으로 변경
- next에서 제공하는 서드파티가 로깅 되지 않아 이전 로깅 방식으로 회귀하였습니다.
arguments를 그대로 쓰는 코드를 작성했는데, 더 좋은 방식 있으면 리뷰 남겨주세요... (lint 에러 발생)
> [fix] next 로깅 방식에서 이전 로깅 방식으로 변경

- src/pages/webview/campusinfo/index.tsx
- Close #1004
- 기능 :웹뷰 교내 시설물 정보 레이아웃 제거
- issue : #1004
웹뷰 교내 시설물 정보 컴포넌트에 빈 레이아웃을 설정하여 기본 레이아웃을 렌더링 되지 않도록 수정했습니다.
> [교내 시설물 정보] 웹뷰 환경에서 레이아웃 렌더링
