BCSDLab/KOIN_WEB_RECODE

src/components/common/Footer/index.tsx, src/components/common/Header/index.tsx
> 급한 머지 죄송합니다. 다음부터는 모든 todo를 끝마치고 머지하겠습니다.
- megamenu__trigger에 mouseout시에 blur처리 추가
- footer 리스트 렌더링 시 key props 없어서 추가
=> Feature/#2 추가 PR

src/pages/Auth/LoginPage/LoginPage.module.scss, src/pages/Auth/LoginPage/index.tsx
자동로그인 체크박스 구조 개선
- label > input 구조로 변경 (span 제거)
- input의 display를 유지하고 UI와 동기화
- label의 불필요한 드래그 block
- 실제 checkbox가 input과 동일화되어 복잡한 접근성 문제 해결 가능
=> Feature/#5 자동로그인 체크박스 수정

src/index.scss, src/pages/Auth/LoginPage/LoginPage.module.scss, yarn.lock
=> Feature/#6 폰트 추가

src/api/store/APIDetail.ts, src/api/store/entity.ts, src/api/store/index.ts, src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/index.tsx, src/utils/ts/getDayOfWeek.ts
상점 API 대응 수정
- 상세: 요일 별 개점 폐점 시간 변환, 메뉴 리스트 관련 로직 변경
- 주변 상점 리스트:  요일별 개점 폐점 시간에 대한 로직 변경
=> [상점 API 에러 수정] 상점 API 에러 수정

src/components/common/Header/index.tsx
=> [공통] 페이지에 대한 Header 스타일 변경

.gitignore, src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts, src/pages/Store/StoreDetailPage/hooks/useStoreMenus.ts, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/index.tsx
=> [상점페이지] 주변 상점 업데이트 관련 로직 수정

src/api/auth/APIDetail.ts, src/components/common/Header/Header.module.scss, src/components/common/Header/index.tsx, src/utils/hooks/useLogout.ts
=> feat: 로그아웃추가, 회원가입 닉네임변경 적용

src/components/TimetablePage/DefaultPage/index.tsx, src/pages/IndexPage/IndexPage.module.scss, src/pages/IndexPage/components/IndexBus/IndexBus.module.scss, src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts, src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexCafeteria/index.tsx, src/pages/IndexPage/components/IndexStore/IndexStore.module.scss, src/pages/IndexPage/components/IndexTimetable/IndexTimetable.module.scss, src/pages/IndexPage/components/IndexTimetable/index.tsx, src/pages/IndexPage/index.tsx, src/pages/TimetablePage/index.tsx
=> [메인페이지] 시간표 페이지 추가 & 모바일 순서 변경

src/pages/BusPage/ts/busModules.ts
=> [버스페이지] 시간 안맞는 문제 수정

src/pages/IndexPage/IndexPage.module.scss, src/pages/IndexPage/components/IndexBus/IndexBus.module.scss, src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
=> [UI수정] 모바일 UI 수정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/SignupPage/index.tsx
=> fix: 회원가입 sha-256추가, 경로변경

public/index.html, src/components/Post/Pagination/index.tsx, src/components/common/Header/index.tsx, src/pages/IndexPage/components/IndexStore/IndexStore.module.scss, src/pages/Room/RoomPage/hooks/useMarker.ts, src/pages/Room/RoomPage/hooks/useNaverMap.ts, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/index.tsx
=> [#78] 웹 페이지 수정

.github/workflows/PICK_REVIEWER.yml, .github/workflows/reviewer.json, src/components/common/Header/index.tsx, src/pages/Auth/ModifyInfoPage/index.tsx, src/pages/Auth/SignupPage/index.tsx, src/static/terms.ts, src/utils/hooks/useUserInfo.ts
- 기능 : 유저정보 전역화, gender 값 오류 수정
- issue : #78
=> [78-3] 유저정보 전역화 및 gender 값 안들어가는 이슈 수정

src/components/common/Header/index.tsx, src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss, src/pages/Auth/ModifyInfoPage/components/UserDeleteModal/UserDeleteModal.module.scss, src/pages/Auth/ModifyInfoPage/components/UserDeleteModal/index.tsx, src/pages/Auth/ModifyInfoPage/hooks/useUserDelete.ts, src/pages/Auth/ModifyInfoPage/index.tsx
- Close #87 
- 기능 : confirm 제거 이후 모달창 띄우기 추가
- issue : #87
=> [#87] confirm 사용 불가로 인한 모달창 생성

src/static/category.ts
- Close #96 
- 기능 : nav바 주변 상점 이동 링크 수정
- issue : #96 
NAV바 주변 상점 이동 링크 **전체보기 카테고리**로  임시 수정
=> [#96] 주변 상점 가기 링크 수정

public/index.html
=> feat: gtm main Merge 에러

.github/workflows/CHECK_PR_MERGED.yml
PR이 변경되었을때 액션을 트리거하려면 [이렇게](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges) 해야한다고 해서 해당 내용 반영합니다.
현재 잘 들어간 모습
=> feat: PR병합될 때 호출되게끔 변경

.github/workflows/CHECK_PR_MERGED.yml
pr link를 가져오지 못하고있어 PR에 approve가 달리는 시점에 액션을 트리거하게 수정합니다.
=> [편의] pr approve시점으로 액션 실행시간 변경

src/components/TimetablePage/DefaultPage/index.tsx, src/pages/IndexPage/components/IndexTimetable/index.tsx
- Close #131 
- 메인페이지 
- 기능 : 메인페이지에 시간표를 볼 수 있도록 수정
- issue : #131
=> [시간표] 메인페이지의 시간표 수정

src/pages/IndexPage/components/IndexTimetable/IndexTimetable.module.scss, src/pages/IndexPage/components/IndexTimetable/index.tsx
- Close #134
- 기능 : 메인페이지의 시간표를 누르면 `시간표` 페이지로 이동
- issue : #134
=> [시간표] 메인페이지 시간표 라우팅 추가

src/components/TimetablePage/DefaultPage/index.tsx
- Close #135 
- 기능 : 나의 시간표가 화면을 넘어갑니다.
- issue : #135 
나의 시간표 높이를 수정했습니다.
=> [시간표] 나의 시간표 화면 넘어가는 이슈 해결

src/components/common/LogPage/index.tsx, src/lib/gtag.ts, src/utils/ts/uuidGenerater.ts
- Close #110 
- 기능 : UUID 유틸 함수 추가 및 UserID 수집 기능 추가
- issue : #110
=> UUID와 학번을 통한 UserID GA4 기능 추가

src/utils/recoil/semester.ts
- Close #142
- 기능 : 
- issue :
=> fix: getLoadable async하게 변경

src/api/store/entity.ts, src/components/common/UpdateInfo/UpdateInfo.module.scss, src/pages/Store/StoreDetailPage/MenuTable/MenuTable.module.scss, src/pages/Store/StoreDetailPage/MenuTable/index.tsx, src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss, src/pages/Store/StoreDetailPage/index.tsx, src/static/menu.ts, src/utils/hooks/useMoveScroll.ts
- Close #139 
- 기능 : 음식점 상세 UI 개편
- issue : #139 
- UI 변경했습니다.
- 특정 위치로 스크롤이 이동하는 `useMoveScroll` 훅을 추가했습니다.
=> [음식점 상세] 음식점 상세 메뉴 페이지 개편

src/pages/Auth/LoginPage/index.tsx, src/utils/recoil/index.ts, src/utils/ts/cookie.ts
- Close #182
- 기능 : accessToken을 담고 있는 cookie를 session으로 변경
- issue : #182
- `setCookie`에서 모든 accessToken을 session으로 설정하도록 수정
=> [유저 로그인] 무효화 된 accessToken 처리

src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexCafeteria/index.tsx
- Close #184 
- 기능 : 식단 카드 클릭 이벤트 범위 확장
- issue : #184 
* 식단 카드 클릭 이벤트 범위 확장하였습니다.
=> [식단] 식단 카드 클릭 이벤트 범위 확장

src/index.tsx
- Close #192 
- 기능 : queryClient 재정의
- issue : #192 
[코인 오너 pr](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/297)을 참고해주세요!
=> [공통] queryClient 재정의

public/index.html, src/pages/Store/StoreDetailPage/index.tsx, src/utils/hooks/useLogger.ts
=> action 커스텀 이벤트 추가

src/components/Post/HotPost/index.tsx, src/components/common/Footer/index.tsx, src/components/common/Header/index.tsx, src/pages/BusPage/BusLookUp/index.tsx, src/pages/BusPage/BusTimetable/Timetable.tsx, src/pages/BusPage/BusTimetable/index.tsx, src/pages/IndexPage/components/IndexBus/index.tsx, src/pages/IndexPage/components/IndexCafeteria/index.tsx, src/pages/IndexPage/components/IndexNotice/index.tsx
- Close #205 
- 기능 : 캠퍼스팀 로깅 작업
- issue : #205 
캠퍼스팀 로깅을 추가했습니다.
=> [식단, 버스, 커뮤니티] 캠퍼스팀 로깅 작업

src/components/common/Header/index.tsx, src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/index.tsx
- Close #212 
- 기능 : 비즈니스팀 로깅 작업
- issue : #212
비즈니스팀 로깅을 추가했습니다
저번 pr은 develop에 로그를 심었기때문에 main에 다시 로깅했습니다..
pr이 머지되면 dev에서 main을 머지 받고 충돌 해결 후 푸시하겠습니다..................
=> [비즈니스] 비즈니스팀 로깅 작업

src/components/common/Header/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/SignupPage/index.tsx
- Close #208 
- 기능 : 유저팀 유저 로그 추가 했습니다.
- issue : #208
- DA에서 작성한 [1차 로그선정 시트](https://docs.google.com/spreadsheets/d/1gdM4oX3t6LTOfC1Dkrc5Bwnfm-0jTyAzmflnvGnnMss/edit#gid=723088835)를 참고하여 로그 추가하였습니다.
=> [유저] 유저팀 로그 추가

README.md
=> test acation

src/pages/Cafeteria/Cafeteria.module.scss, src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss, src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/index.tsx
- Close #225 
- 기능 : 식단 웹뷰 버그 해결
- issue : #225 
식단 페이지에서 새로 추가된 기능들 중 의도대로 동작하지 않는 기능을 수정하였습니다.
* 아점저 선택 드롭박스로 선택해도 변하지 않는 문제 해결
* 아점저 선택 드롭박스를 열었다가 그 열었던 버튼으로 닫히지 않는 문제 해결
* 지난 주 이전 주에서 품절 메뉴에 품절되었다는 svg(칩x)가 나타나는 문제 해결
* svg와 같이 품절되었습니다 글자 안 나오는 문제
* 품절 사진도 상세보기 가능
* 사진x 품절인 경우 svg만 보이기
=> [식단] 식단 웹뷰 문제 해결

src/pages/IndexPage/components/IndexStore/IndexStore.module.scss, src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/Store/StorePage/StorePage.module.scss, src/pages/Store/StorePage/index.tsx
- Close #228 
- 기능 : 모든 카테고리를 보여주도록 수정
- issue : #228 
이제 10개 카테고리를 전부 보여줍니다.
da분이 ab테스트를 마치면 안드로이드, ios와 맞춰 전체보기 카테고리를 없앨 예정입니다.
이제 미용실 카테고리는 뷰티 카테고리가 되고, 기타 카테고리는 기타/콜밴 카테고리가 됩니다.
모바일에서 카테고리 이름을 4글자 제한을 해제했습니다.
=> [주변상점] 모든 카테고리를 보여주도록 수정

src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss
- Close #233
- 기능 : 식단 상세 사진 모달 fit 방식 변경
- issue : #233 
식단 상세 사진 모달 fit 방식을 cover에서 contain으로 변경하였습니다.
=> [식단] 식단 상세보기 사진 비율 조정

src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/AuthenticateUserModal.module.scss
- 기능 : css `start`를 `flex-start`로 수정
- issue : 
justify-content `start` 를 `flex-start` 로 수정
=> [유저] 빌드 실패 해결

src/components/TimetablePage/Listbox/Listbox.module.scss, src/components/TimetablePage/Listbox/index.tsx, src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss, src/pages/Auth/ModifyInfoPage/index.tsx, src/pages/Auth/SignupPage/hooks/useSignup.ts, src/pages/Auth/SignupPage/index.tsx, src/utils/ts/apiClient.ts
- 기능 : 유저팀의 유저 도메인 QA 이슈 해결
- issue : 
- 회원가입 시 에러 핸들링 추가(이미 존재하는 아이디에 대한 에러 핸들링 추가)
- `정보 수정`, `회원가입` 페이지에 학부 선택을 드롭박스로 전체 통일 ([관련 스레드](https://bcsdlab.slack.com/archives/C06N40APJAK/p1715304131083289))
- `정보 수정` 페이지 문구 중 **비밀번호 필수**를 **비밀번호 선택**으로 변경
- `정보 수정`, `회원가입` 페이지에 학부 선택, 성별 선택 드롭박스 디자인 변경
- 토큰 무효화 된 이후 에러 핸들링이 되지 않아 페이지에 접근 불가하여 해당 에러 핸들링 추가
토큰 무효화 된 이후 에러 핸들링은 크리티컬한 이슈라고 생각해서 이 부분을 중점적으로 리뷰 해주시면 감사하겠습니다!
=> [유저] 유저 QA 이슈 해결

src/lib/gtag.ts, src/pages/Store/StoreDetailPage/EventTable/components/EventCard/EventCard.module.scss
- Close #257 
- 기능 : 
- issue : #257 
lint rule 무시 주석을 추가
=> [공통] lint 오류 해결

src/pages/Store/StoreDetailPage/index.tsx, src/utils/hooks/useScrollLogging.ts
- 기능 : 로깅 undefined 문제 해결([스레드](https://bcsdlab.slack.com/archives/C06N99Z3D45/p1715357634383539))
- issue : 
- 로깅 에러문제 해결했습니다.
=> fix: undefined 문제 해결

src/index.scss
- Close #269
- 기능 : iOS 기본폰트 색상 대응
- issue : #269
iOS 기본폰트 색상이 파란색이여서 전역적으로 검정색으로 적용해줬습니다.
배포 후 캐시삭제하고 iOS환경에서 직접 확인 할 수 있습니다.
=> [공통] iOS 폰트색상 전역적으로 수정

src/index.scss
- Close #269 
- 기능 : iOS 기본 폰트 색상 수정
- issue : #269
기존 모든 태그에서 색상을 변경하도록 했으나, `a` `button`태그의 색상만 변경되도록 수정했습니다.
빌드 후 iOS환경에서 확인 가능합니다.
=> [공통] iOS 기본 폰트 색상 수정

src/pages/Cafeteria/Cafeteria.module.scss, src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss, src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/MobileMenuBlock.module.scss, src/pages/Cafeteria/MobileCafeteriaPage/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss, src/pages/Cafeteria/PCCafeteriaPage/index.tsx
- Close #271 
- 기능 : 식단 주의 문구 추가
- issue : #271 
pc 뷰와 모바일 뷰 각각 식단에 "식단 정보는 운영 상황 따라 변동될 수 있습니다." 문구를 추가하였습니다.
프로덕트에 적용되어야 할 내용이기 때문에 메인 브랜치에서 핫픽스로써 작업하였습니다.
=> [식단] 주의 문구 추가

src/pages/Store/StoreDetailPage/index.tsx
- 기능 : 웹뷰에서 전화하기가 가능하도록 변경
e.preventdefault()로 전화하기 이벤트를 막고 있는 것 같습니다.
머지 후 develop에서 main 머지 받겠습니다
=> [hotfix] 웹뷰에서 전화하기가 가능하도록 변경

public/index.html
- 기능 : 자동번역을 막기 위해 메타 태그 추가
- issue : #
- 자동번역 때문에 예상치 못한 텍스트 오류가 있어 자동번역을 끄기 위해 메타 태그 추가했습니다.
[**에러**]
=> [공통] 자동번역 삭제

src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
=> 버튼에 글씨가 제대로 안보이는 현상 수정

src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
- Close #287
- 기능 : 아침 식단 사진 삭제
- issue : #287
아침 식단 사진 칸을 삭제하였습니다.
=> [식단] 아침 식단 사진 삭제

src/App.tsx, src/components/common/LogPage/index.tsx, src/lib/gtag.ts, src/utils/hooks/useLogger.ts
- Close #303 
- 기능 :  React-Helmet 관련 이벤트 로거 문제 수정
- issue : #303 
1. GA 이벤트에 대한 콘솔이 프로덕션에 찍히는 것을 방지하기 위해 조건문 추가했습니다.
2. 로그 페이지 1초 딜레이로 pageView 이벤트 활성화를 진행했습니다.
3. 클릭 이벤트 중복 방지로 조건문 추가해두었습니다.
4. title 자체가 업데이트 되지 않는 문제가 종종 발생해서 useEffect로 해당 내용 업데이트 될 수 있도록 했습니다. => DOM tree Head  title 접근 dept가 깊지 않아 성능 문제는 없습니다.
=> [GA] GA 관련 React-Helmet 관련 Title과 Route가 맞지 않는 문제 수정

public/index.html, src/App.tsx, src/components/common/LogPage/index.tsx
- Close #73 
- 기능 : USER_ID 수집 관련 기능 추가
- issue : #73 
USER_ID 수집이 제대로 되지 않던 로직 문제를 해결했습니다.
=> [HotFix] userId 에러 수정

.vscode/settings.json, src/components/TimetablePage/Listbox/NewListbox.module.scss, src/components/TimetablePage/Listbox/index.tsx, src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx, src/pages/Timetable/components/CustomLecture/CustomLecture.module.scss, src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/CustomLectureDefaultInput.module.scss, src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/index.tsx, src/pages/Timetable/components/CustomLecture/CustomLectureLocationTimeSetting/index.tsx, src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/CustomLectureTimeInput.module.scss, src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/index.tsx, src/pages/Timetable/components/CustomLecture/index.tsx, src/static/timetable.ts
- 기능 : 시간표 수정 내부 직접 추가의 UI를 구현하였습니다.
- issue : #319 
* 직접 추가 UI를 구현하였습니다.
* API 요청 구조에 따라 UI 작업에 대한 구조가 변경될 가능성이 높습니다.
* 현재 API 명세가 없어 시간표 저장 요청이 담기는 구조를 파악하기 어려워 임의로 form 구조를 만들어 놓았습니다. 이후 api 명세를 확인하여 구조 및 [시간 및 장소 추가] 기능의 연장 개발이 필요합니다.
=> [시간표] 직접 추가 UI 구현

src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
- 기능 : 시간표 저장 버튼 기능 수정
- issue : #
시간표 저장 버튼에 예시로 넣어둔 토스트 기능을 삭제하고 이전 기능으로 수정했습니다!
=> [시간표] 시간표 저장 버튼 기능 수정

src/pages/TimetablePage/components/LectureList/index.tsx
- Close #349 
- 기능 : 동일한 과목을 추가할 수 없게 했습니다.
- issue : #349 
toast문구 괜찮은지 확인부탁드립니다.
=> [hotfix] 시간표 동일한 과목 추가

src/components/common/Header/MobileHeader/Panel/index.tsx
- Close #352
- 기능 : 사이드 네비바 스크롤 막기
- issue : #352
사이드 네비바에서 스크롤 막기
=> [공통] 사이드 네비바에서 스크롤 막기

src/index.scss
- Close #354
- 기능 : 폰트 다운 문제 수정
- issue : #354
폰트 확장자 수정
=> 폰트 다운 문제 수정

src/api/timetable/entity.ts, src/components/TimetablePage/Listbox/NewListbox.module.scss, src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss, src/pages/Timetable/components/Curriculum.tsx, src/pages/Timetable/components/LectureList/LectureList.module.scss, src/pages/Timetable/components/SemesterList/SemesterList.module.scss, src/pages/Timetable/components/SemesterList/index.tsx
- 기능 : 디자인 수정
- issue : #333 
input 박스 너비 수정 및 단순 UI 수정
=> [유저] 디자인 수정

src/pages/Auth/AuthPage/index.tsx
- Close #362
- 기능 : 메인 페이지로 돌아가지 않는 에러를 `절대 경로`를 통해 수정
- issue : #362
=> [hotfix] 메인페이지로 돌아가지 않는 에러 수정

src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx, src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/index.tsx, src/pages/Cafeteria/hooks/useDatePicker.ts, src/pages/Cafeteria/index.tsx, src/pages/IndexPage/IndexPage.module.scss, src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexCafeteria/index.tsx, src/utils/ts/cafeteria.ts
- 기능 : 식단 주기 변경, 툴팁 추가
- issue : #348 
- 웹 페이지뷰에서 확인할 수 있습니다.
- localStorage를 활용했습니다. 기기당 상호작용 1회 시 표시되지 않습니다.
- 상호작용 : 툴팁 텍스트 클릭 시, 닫기 버튼 클릭 시
=> [식단] 식단 주기 변경 및 툴팁 추가

src/App.tsx, src/components/Cafeteria/CafeteriaInfo/CafeteriaInfo.module.scss, src/components/Cafeteria/CafeteriaInfo/index.tsx, src/components/common/Header/MobileHeader/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss, src/pages/Cafeteria/MobileCafeteriaPage/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx, src/pages/IndexPage/IndexPage.module.scss, src/pages/IndexPage/index.tsx, src/utils/hooks/auth/useLoginRedirect.ts, src/utils/hooks/layout/useResetHeaderButton.ts, src/utils/ts/apiClient.ts, src/utils/ts/auth.ts, src/utils/zustand/headerButtonStore.ts
- 기능 : QA 이슈 수정
- issue : #386
이 pr은 `feat/#386-campus-qa`로 머지될 것입니다.
=> [캠퍼스] QA 이슈 수정

src/pages/BusPage/BusTimetable/BusTimetable.module.scss, src/pages/BusPage/BusTimetable/Timetable.tsx, src/pages/IndexPage/components/IndexBus/IndexBus.module.scss, src/pages/IndexPage/components/IndexBus/index.tsx
- 기능 : 캠퍼스 QA 수정
- issue : #386
- 시내버스 경로설정 버튼이 드롭다운에서 버튼으로 변경되었습니다.
- 메인화면에서 버스카드 클릭시 시간표로 이동합니다.
=> [캠퍼스] QA 이슈 수정(버스)

src/lib/gtag.ts
DA님의 요구사항으로 스테이지에서 콘솔을 통해 이벤트를 확인할 수 있도록 변경했습니다
=> [공통] 스테이지 환경에서 콘솔 테이블을 확인할 수 있도록 수정

src/assets/svg/bubble-tail-bottom.svg, src/components/Cafeteria/CafeteriaInfo/CafeteriaInfo.module.scss, src/components/Cafeteria/CafeteriaInfo/index.tsx, src/components/common/Header/MobileHeader/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/BusPage/BusTimetable/BusTimetable.module.scss, src/pages/BusPage/BusTimetable/Timetable.tsx, src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss, src/pages/Cafeteria/MobileCafeteriaPage/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/PCDiningBlocks.module.scss, src/pages/Cafeteria/PCCafeteriaPage/index.tsx, src/pages/Cafeteria/hooks/useDatePicker.ts, src/pages/IndexPage/IndexPage.module.scss, src/pages/IndexPage/components/IndexBus/IndexBus.module.scss, src/pages/IndexPage/components/IndexBus/index.tsx, src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexCafeteria/index.tsx, src/pages/IndexPage/index.tsx, src/utils/hooks/auth/useLoginRedirect.ts, src/utils/hooks/layout/useResetHeaderButton.ts, src/utils/ts/apiClient.ts, src/utils/ts/auth.ts, src/utils/ts/cafeteria.ts, src/utils/zustand/headerButtonStore.ts
- Close #386
- 기능 : 캠퍼스팀 QA 브랜치를 develop으로 merge합니다.
- issue : #386
- #392 
- #393
- #396
각 PR을 #386 에 merge한 뒤 develop에 배포하는 PR입니다.
각 PR별로 코드리뷰가 완료된 상태입니다.
충돌사항이 있는지 위주로 봐주시면 감사하겠습니다.
=> [캠퍼스] QA 이슈 해결

src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
- Close #409 
- 기능 : 인덱스 페이지 식단 글자 깨짐
- issue : #409
=> [식단] 인덱스 페이지 식단 글자 깨짐

src/components/TimetablePage/Listbox/index.tsx, src/components/common/Footer/index.tsx, src/components/common/Header/MobileHeader/Panel/index.tsx, src/components/common/Header/MobileHeader/index.tsx, src/components/common/Header/PCHeader/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/IndexPage/components/IndexTimetable/index.tsx, src/pages/TimetablePage/MobilePage/index.tsx, src/pages/TimetablePage/components/Curriculum.tsx, src/pages/TimetablePage/components/LectureList/index.tsx, src/pages/TimetablePage/components/MyLectureTimetable/SemesterListbox.tsx, src/pages/TimetablePage/components/MyLectureTimetable/index.tsx, src/utils/hooks/analytics/useLogger.ts
- Close #414 
- 기능 : 유저팀 로깅 추가
- issue : #414 
- approve 받고 오늘까지 merge해야 합니다...!
- 로그인 부분 로그 추가
- 시간표 부분 로그 추가
- 헤더, 푸터, 햄버거 공통(CAMPUS, BUSINESS, USER) 로그 추가
- `actionEventClick`의 `category`(구글 시트에서 event_category)가 `button`인 것을 `click`으로 고쳤습니다.
=> [유저] 유저팀 로깅 추가

src/pages/IndexPage/components/IndexBus/index.tsx
- Close #413
- 기능 : 캠퍼스팀 모바일 로깅 추가
- issue : #413
- 모바일 웹 환경에서 버스카드를 스크롤 할 때 로깅을 추가했습니다.
=> [캠퍼스] 캠퍼스팀 모바일 로깅 추가

src/pages/StoreReviewPage/ReviewForm/ReviewForm.module.scss, src/pages/StoreReviewPage/ReviewForm/ReviewForm.tsx
- Close #411 
- 기능 : 리뷰하기 QA 반영
- issue : #411 
- 메뉴 추가 시 빈 메뉴가 보이지 않도록 제외했습니다.
- 리뷰 작성페이지로 뒤로가기를 막았습니다.
- 업스크롤 추가했습니다.
=> [비즈니스] 리뷰하기 QA 반영

src/components/common/CommonCheckBox/CheckBox.module.scss, src/components/common/CommonCheckBox/index.tsx, src/components/common/Header/MobileHeader/Panel/index.tsx, src/components/common/Header/PCHeader/index.tsx, src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/ReviewReporting.module.scss, src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/components/ReportingLabel/ReportingLabel.module.scss, src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/components/ReportingLabel/index.tsx, src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
- Close #422
- 기능 : 리뷰 기능 QA수정
- issue : #422
-  [x] 사이드바에 메뉴수정 메뉴가 보임
-  [x] 신고하기 라벨클릭
-  [x] 신고하기 기타 글자 수제한 오류
-  [x] 기타 텍스트 스페이스바 입력시 오류
-  [x] 신고하기 subtitle 자간
=> [주변상점] 리뷰 기능 QA 수정

src/api/notice/APIDetail.ts, src/components/Post/PostDetailHeader/index.tsx, src/pages/Notice/NoticeDetailPage/index.tsx
- Close #430
- 기능 : api path 변경 대응
- issue : #430
🚨 이 pr은 메인을 대상으로 합니다!
백엔드 측에서의 공지사항 api 수정 배포와 발 맞춰 핫픽스 진행합니다.
현재 디벨롭 코드에 배포 준비가 되지 않은 코드가 있어서 디벨롭-메인 머지가 아닌 메인에서 핫픽스를 잔행합니다.
1. /articles/hot/list -> /articles/hot
2. comment_count 필드 삭제 및 사용 중인 부분 삭제
=> [핫픽스] api path 변경 배포 대응

src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
- 기능 : 
- issue : #
150글자 제한 오류 수정
=> [주변상점] 리뷰 신고하기 기타 글자수 제한 로직 수정

src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/IndexPage/index.tsx, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/index.tsx, src/utils/hooks/analytics/useLogger.ts, src/utils/hooks/analytics/useScrollLogging.ts
- 기능 : 
- issue : #
찍히지 않는 로깅 정보
event_category가 button으로 나오는 오류
등 로깅 에러 수정
=> [비즈니스] 로깅 에러 수정

src/pages/IndexPage/components/IndexCafeteria/index.tsx
- Close #440
- 기능 : 캠퍼스 식단 로깅 버그 수정
- issue : #440
- 메인페이지에서 특정코너를 두번눌러야 반영되는 버그를 수정했습니다.
=> [캠퍼스] 로깅 버그 수정

src/components/TimetablePage/LectureTable/LectureTable.module.scss, src/components/TimetablePage/LectureTable/index.tsx, src/components/common/ToggleButton/ToggleButton.module.scss, src/components/common/ToggleButton/index.tsx, src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss, src/pages/Timetable/components/LectureList/LastUpdatedDate.tsx, src/pages/Timetable/components/LectureList/LectureList.module.scss, src/pages/Timetable/components/LectureList/index.tsx, src/utils/hooks/useTimetableDayListV2.ts
- Close #423 
- 기능 : `시간표에 추가한 과목` 버튼 토클 시 내가 시간표에 담은 과목을 볼 수 있게 해줍니다.
- issue : #423 
- `ToggleButton` 공통 컴포넌트 생성
- 강의 목록 UI 개선(행 높이, 글자 크기, 테이블 높이 조정)
- 최근 업데이트 UI 개선
- 시간표에 추가한 과목 리스트 컴포넌트 생성
- 추가로 안 쓰거나 요소 간 중복된 `style` 속성을 제거하고 `class`를 삭제했습니다. 코드 순서도 `tsx`에 작성된 순서에 맞게 두었습니다.
- 개선된 강의 목록 UI
- 내가 담은 강의 목록 UI
- 내가 담은 강의 목록에서 강의 호버 시 삭제 버튼 생성
=> [시간표] 나의 강의 목록

src/components/common/Header/MobileHeader/Panel/index.tsx, src/pages/BusPage/BusTimetable/Timetable.tsx
- Close #445
- 기능 : 캠퍼스팀 로깅 수정
- issue : #445
- 버스 드롭다운 선택시 로깅이 지연되던 이슈를 해결했습니다.
- 누락된 시내버스 로깅을 추가했습니다.
- 로깅 title 일부를 변경했습니다.
=> [캠퍼스] 캠퍼스팀 로깅 수정

src/components/common/Header/PCHeader/index.tsx, src/utils/hooks/data/useTimetableDayList.ts
- Close #448 
- 기능 :  시간표 페이지에서 헤더 로고 클릭 시 로그를 추가합니다.
- issue : #448 
- 시간표 페이지에서 헤더의 코인 로고를 클릭할 시의 로그를 추가했습니다.
- 추가로 stage 환경에서 가끔 시간표가 안 보이는 현상을 수정했습니다.
=> [유저] 유저팀 로깅 수정

src/api/notice/entity.ts, src/components/Post/Pagination/index.tsx, src/pages/Notice/NoticeListPage/index.tsx
- Close #451
- 기능 : 공지사항 페이징 버그 수정
- issue : #451
- 공지사항에서 바로 다음으로 클릭시 현재 페이지가 undefined여서 생기던 버그를 수정했습니다.
=> [공지사항] 공지사항 페이징 버그 수정 (hotfix)

src/pages/IndexPage/components/IndexNotice/index.tsx, src/pages/IndexPage/components/IndexTimetable/index.tsx, src/pages/Timetable/hooks/useTimetableFrameList.ts
- 기능 : 로그인시 시간표 에러 수정
- issue : #454 
로그인시 기존 시간표가 아닌 새로운 기본시간표가 나오는 에러를 수정했습니다.
[ 로그인시 잘못 나오는 기본 시간표]
[ 로그인 이후 새로고침 하면 나오는 정상적인 시간표]
=> [시간표] 로그인시 시간표 에러 수정

.eslintrc.json, src/components/TimetablePage/Listbox/index.tsx, src/components/TimetablePage/Timetable/index.tsx, src/components/common/CommonCheckBox/index.tsx, src/components/common/KoinToast/index.tsx, src/components/common/LoginRequiredModal/index.tsx, src/components/common/MetaHelmet/index.tsx, src/components/common/Toast/TimetableToast/index.tsx, src/pages/Auth/ModifyInfoPage/index.tsx, src/pages/IndexPage/components/IndexTimetable/index.tsx, src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx, src/pages/TimetablePage/MainTimetablePage/index.tsx, src/pages/TimetablePage/components/Curriculum.tsx, src/pages/TimetablePage/components/LectureList/index.tsx, src/pages/TimetablePage/components/MyLectureTimetable/index.tsx, src/pages/TimetablePage/components/SemesterList/index.tsx
- Close #476 
- 기능 : 없어졌던 유저팀 로깅 코드를 복구합니다.
- issue : #476 
오늘 내로 merge할 수 있으면 좋겠습니당..!
이전에 추가했던 관련 PR입니다!
#416 
#426 
#449
=> [유저] 유저팀 로그 복구

src/pages/TimetablePage/MainTimetablePage/index.tsx, src/pages/TimetablePage/components/MainTimetable/MyLectureTimetable.module.scss, src/pages/TimetablePage/components/TimetableList/index.tsx
- Close #489 
- 기능 : 시간표 추가시 해당 시간표로 이동하게 수정
- issue : #489
=> [시간표] 시간표 추가시 해당 시간표로 이동하게 수정

src/utils/ts/setArticleRegisteredDate.ts
- Close #498
- 기능 : 
- issue : #498
날짜 형식 변경 함수
제가 예전에 잘못 알고 삭제했던 코드를 다시 작성했습니다.
=> [핫픽스] 공지사항 날짜 형식 문제

src/pages/TimetablePage/MainTimetablePage/index.tsx, src/pages/TimetablePage/components/TimetableList/index.tsx, src/pages/TimetablePage/hooks/useAddSemester.ts, src/pages/TimetablePage/hooks/useDeleteSemester.ts
- Close #496 496
- 기능 : 
- issue : #496 
시간표 추가 시 프레임이 이동하지 않던 부분 수정 했습니다.
또한 semesterList (학기 선택) 클릭시 main프레임으로 이동하지 않았던 에러 수정했습니다.
=> [시간표] 시간표 추가시 프레임 이동 수정

src/utils/ts/cafeteria.ts
- Close #508 
- 기능 : 아침, 점심 식단 변경 시간 조정
- issue : #508 
아침, 점심 식단 변경 시간이 조정되었습니다.
기존) 10시 30분
변경 후) 오전 9시
핫픽스 내용입니다.
main에 바로 들어가는 PR이며 PR 반영되면 develop에서는 cherrypick으로 반영하겠습니다.
=> [식단] 아침, 점심 식단 변경 시간 조정

src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/TimetableSettingModal.module.scss, src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
- Close #486 
- 기능 : label 태그 활용으로 영역 수정
- issue : #486 
기존의 div 태그이던 것을 label로 수정하여 클릭 영역을 수정하였습니다.
커서를 포인터로 바꾸었습니다.
- [] It's submitted to the correct branch, not the `develop` branch unconditionally?
=> [시간표] lable로 영역 수정

src/components/common/Header/MobileHeader/index.tsx
상점 메인 화면에서 뒤로 가기 시 뒤로가기가 불가능한 현상을 수정했습니다.
정확하진 않지만 아마 누군가 경로를 마이그레이션하면서 생긴 오류 같아요
1. id가 undefined일때 확실히 api 요청을 하지 않도록 수정
2. 상점 상세 페이지에서 뒤로가기 시 바로 이전 페이지로 이동하도록 수정
=> [버그픽스] 주변상점에서 뒤로 가기 시 생기는 버그 수정

src/pages/TimetablePage/hooks/useTimetableV2Mutation.ts
- Close #520 
- 기능 : 
- issue : #
=> fix: 오타 수정

src/api/abTest/APIDetail.ts, src/api/abTest/entity.ts, src/api/abTest/index.ts, src/api/index.ts, src/interfaces/APIRequest.ts, src/pages/BoardPage/index.tsx, src/utils/hooks/abTest/useABTestView.ts
AB테스트를 위한 hook입니다.
const token = useTokenState();
useABTestView(테스트 변수명, token)
이렇게 사용하시면 됩니다.
테스트 변수명은 어드민 페이지 ab 테스트 상세 페이지 상단 테이블의 변수를 의미합니다.
=> [common] AB테스트 사용자 뷰 변수 받는 공용 훅 구현

src/pages/TimetablePage/components/MainTimetable/index.tsx, src/pages/TimetablePage/components/SemesterList/index.tsx, src/pages/TimetablePage/components/TimetableList/TimetableList.module.scss, src/pages/TimetablePage/components/TimetableList/index.tsx
- 기능 :  학기 없을 시 문구 추가 및 버튼 disable 처리
- issue : #529 
- 학기가 존재하지 않을 때, 학기는 존재하지만 프레임은 존재하지 않을 때 문구를 추가했습니다. 
- 학기가 존재하지 않을 때 수정 버튼을 disable 처리 했습니다.
=> [시간표] 학기 없을 시 문구 추가 및 버튼 disable 처리

src/pages/IndexPage/components/IndexTimetable/index.tsx, src/pages/TimetablePage/components/MainTimetable/index.tsx, src/pages/TimetablePage/components/SemesterList/index.tsx, src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
- Close #537 
- 기능 :  `IndexPage`에서 최신 학기 제대로 불러오기
- issue : #537 
- `IndexPage`에서 보유 학기 중 가장 최신 학기를 불러오도록 설정했습니다.
- 현재 보고 있는 학기 삭제 시 보유 학기 중 가장 최신 학기로 이동하도록 했습니다.
- 시간표 프레임이 없는 경우 빈 시간표를 보여주도록 했습니다.
=> [hotfix, 시간표] 학기 관련 이슈

.github/workflows/reviewer.json
- Close #540 
- 기능 : 유저팀 리뷰어를 수정합니다.
- issue : #540 
- 기존 유저팀인 윤해진님(@haejinyun)과 김도훈님(@dooohun)이 이번 스프린트를 참여하지 않기로 하여 리뷰어에서 제외하였고, 새로 들어온 서예진님(@Yejin0070)을 추가했습니다.
=> [유저] 유저팀 리뷰어 수정

src/components/common/Header/MobileHeader/Panel/index.tsx, src/components/common/Header/PCHeader/index.tsx, src/pages/CampusInfo/CampusInfo.module.scss, src/pages/CampusInfo/index.tsx, src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/Store/StoreBenefitPage/index.tsx
- 기능 : 
- issue : #
ab 로깅 이벤트 네임 수정
스테이지 사장님 페이지 진입점 링크 수정
=> [주변상점] eventname 수정, 스테이지 사장님 진입점 링크 수정

src/pages/Store/StorePage/components/DesktopStoreList/index.tsx
- Close #549 
- 기능 : 준비 중 가게 스페이스 추가
- issue : #549
=> [hotfix] 준비 중 가게 스페이스 추가

src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss, src/pages/TimetablePage/components/SemesterList/index.tsx
- Close #556 
- 기능 : 학기 추가하기 버튼 스타일 수정
- issue : #556
=> [시간표] 학기 추가하기 버튼 스타일 수정

src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx, src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
- Close #568 
- 기능 : 식단 좋아요 삭제
- issue : #568 
식단 좋아요 기능을 삭제하였습니다.
=> [식단] 식단 좋아요 삭제

src/components/TimetablePage/LectureTable/index.tsx, src/pages/TimetablePage/components/Curriculum/index.tsx, src/pages/TimetablePage/components/CustomLecture/index.tsx, src/pages/TimetablePage/components/InducingLoginModal/index.tsx, src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/DownloadTimetableModal.module.scss, src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx, src/pages/TimetablePage/components/SemesterList/AddSemesterModal/index.tsx, src/pages/TimetablePage/components/Timetable/index.tsx
- Close #564 
- 기능 :  로컬 콘솔에서 뜨는 에러를 수정했습니다.
- issue : #564 
크게 두 가지 부분에서 에러가 발생했습니다.
> Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
> Element with focus: button
1. `aria-hidden=true`인 요소 내에서 `focus`되는 부분(click 등..)이 생기는 경우
--> aria-hidden을 삭제했습니다.
> Each child in a list should have a unique "key" prop.
2. 배열 내 요소에 key값을 설정하지 않은 경우
--> key값을 추가했습니다.
=> [시간표] 콘솔 에러 해결

src/pages/TimetablePage/components/CustomLecture/index.tsx
- Close #572 
- 기능 : 장소에 쉼표를 추가하지 못하도록 했습니다.
- issue : #572 
- 장소 placeholder에 쉼표 추가 안내 문구를 추가했습니다.
- 장소에 쉼표를 포함하고 일정 저장 시 에러 토스트를 띄웁니다.
=> [hotfix, 시간표] 장소에 쉼표 입력 방지

src/api/store/APIDetail.ts, src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/Store/StoreDetailPage/index.tsx, src/pages/Store/StorePage/components/DesktopStoreList/DesktopStoreList.module.scss, src/pages/Store/StorePage/components/DesktopStoreList/index.tsx, src/pages/Store/StorePage/components/SearchBar/index.tsx, src/pages/Store/StorePage/components/SearchBarModal/SearchBarModal.module.scss, src/pages/Store/StorePage/components/SearchBarModal/index.tsx, src/pages/Store/StorePage/hooks/useCategoryList.ts, src/pages/Store/StorePage/index.tsx, src/utils/hooks/analytics/useScrollLogging.ts
- 기능 : 서브 스프린트 QA 수정
- PC 주변상점 카드에 리뷰가 보이도록 카드를 리디자인을 진행
- 모바일 리스트가 나오지 않는 현상 수정
- 모바일 상점에서 별점 리뷰 역순되지 않는 에러 수정
- 모바일 검색 시 자동 완성 기능 및 랜딩 기능 추가
훅에서 몇가지 오타로 된 부분도 수정했습니다.
https://github.com/user-attachments/assets/475d6c42-5d44-4530-a159-92167c50849e
=> [비즈니스] QA 수정 

src/pages/TimetablePage/components/MainTimetable/index.tsx
- Close #581 
- 기능 : 시간표 이미지 저장 에러 수정
- issue : #581
=> [시간표] 시간표 이미지 저장 에러 수정

src/api/bus/entity.ts, src/pages/Bus/BusCoursePage/hooks/useBusTimetable.ts
=> [fix] 버스 타입 문제 수정

src/pages/GraduationCalculatorPage/CalculatorHelpModal/CalculatorHelpModal.module.scss, src/pages/GraduationCalculatorPage/CalculatorHelpModal/index.tsx, src/pages/GraduationCalculatorPage/index.tsx
- Close #632 
- 기능 : 졸업학점계산기 도움말 모달
- issue : #632 
졸업학점계산기 도움말 모달 구현
=> [졸업학점계산기] 졸업학점계산기 도움말 모달

src/pages/IndexPage/components/IndexBus/IndexBus.module.scss, src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss, src/pages/IndexPage/components/IndexNotice/IndexNotice.module.scss, src/pages/IndexPage/components/IndexStore/IndexStore.module.scss, src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/IndexPage/components/IndexTimetable/IndexTimetable.module.scss
- Close #637
- 기능 :  인덱스 페이지 폰트, 볼드 통일
- issue : #
=> [메인] 인덱스 페이지 폰트, 볼드 통일

src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss, src/pages/GraduationCalculatorPage/components/ExcelUploader/index.tsx, src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss, src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
- Close #641 
- 기능 : 툴팁 구현
- issue : #641
=> [졸업학점계산기] 툴팁 구현

src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx, src/pages/TimetablePage/MainTimetablePage/index.tsx
- Close #645 
- 기능 : 시간표 페이지 진입 후 뒤로가기가 제대로 안 되는 현상을 수정했습니다.
- issue : #645 
- 시간표 페이지 진입 후 뒤로가기가 제대로 안 되는 현상을 수정했습니다.
=> [hotfix, 시간표] 시간표 페이지 뒤로가기 문제

src/App.tsx
[관련 스레드](https://bcsdlab.slack.com/archives/C06NQT2TY9X/p1738581927544389)
=> [hotfix] 공시사항 오탈자 수정

src/pages/Auth/SignupPage/index.tsx
- Close #661 
- 기능 : 회원가입 시 로깅 추가
- issue : #661 
회원가입 완료 버튼 클릭시 로깅을 추가하였습니다.
=> [유저] 회원가입 시 로깅 추가

src/components/common/LogPage/index.tsx
- Close #663 
- 기능 : user_id 값 변경 
- issue : #663 
기존 user_id 값 : 익명_[13자리 숫자] (anonymous_nickname 값)
변경된 user_id 값 : anonymous_[13자치 숫자]
=> [유저] user_id 값 변경 

src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss, src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss, src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx, src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx, src/pages/GraduationCalculatorPage/index.tsx
- Close #652 
- 기능 : 교양 영역의 개설 목록을 보여주는 모달을 생성합니다.
- issue : #652 
- 교양 컴포넌트에서 교양 영역을 클릭하면 해당 영역의 교양 과목 개설  목록을 보여주는 모달을 보여줍니다. (아직 API 연결을 하지 않아 UI만 보이도록 하였습니다.)
- 컴포넌트 UI 통일을 위해 기존 SemesterCourseTable 스타일 코드를 수정하였습니다.
=> [졸업학점계산기] 교양 과목 목록 모달 생성

src/api/auth/entity.ts, src/components/common/LogPage/index.tsx
- 기능 : 유저아이디 변경
- issue : #668 
기존에 `anonymous_nickname`로 처리하던 `user_id ` 를 단순 정수인 `id` 값으로 변경합니다.
=> [유저] user_Id 변경

src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/GraduationCalculatorAuthModal.module.scss, src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/index.tsx, src/pages/GraduationCalculatorPage/index.tsx
- Close #682 
- 기능 : 로그인 서비스임을 알리는 모달을 구현했습니다.
- issue : #682 
- 비로그인자가 졸학계 페이지 진입 시 로그인 유도 모달을 띄웁니다.
- 페이지 뒷 배경은 모든 기능을 구현하고 정립할 예정입니다.
=> [졸업학점계산기] 로그인 유도 모달 구현

src/pages/GraduationCalculatorPage/GraduationCalculatorPage.module.scss, src/pages/GraduationCalculatorPage/index.tsx, src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss, src/pages/TimetablePage/components/Curriculum/index.tsx
- Close #687 
- 기능 : 시간표 페이지의 커리큘럼 드롭다운 메뉴 너비를 수정했습니다.
- issue : #687 
- 시간표 페이지의 커리큘럼 드롭다운 메뉴 너비를 수정했습니다.
- 졸업학점계산기 페이지 설명에 아우누리 링크를 추가했습니다.
=> [졸업학점계산기] 커리큘럼 드롭다운 메뉴 너비 수정

src/api/timetable/APIDetail.ts, src/api/timetable/entity.ts, src/api/timetable/index.ts, src/components/TimetablePage/Listbox/index.tsx, src/components/common/LogPage/index.tsx, src/components/common/Selector/Selector.module.scss, src/components/common/Selector/index.tsx, src/main.tsx, src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss, src/pages/Auth/ModifyInfoPage/index.tsx, src/pages/Auth/SignupPage/SignupPage.module.scss, src/pages/Auth/SignupPage/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/SemesterLectureListModal.module.scss, src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx, src/pages/GraduationCalculatorPage/components/StudentForm/StudentForm.module.scss, src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx, src/pages/GraduationCalculatorPage/hooks/useCourseType.ts, src/pages/GraduationCalculatorPage/hooks/useExcelUpload.ts, src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts, src/pages/TimetablePage/components/CustomLecture/CustomLecture.module.scss, src/pages/TimetablePage/components/CustomLecture/index.tsx, src/pages/TimetablePage/components/LectureList/DeptListbox.tsx, src/pages/TimetablePage/components/LectureList/LectureList.module.scss, src/pages/TimetablePage/components/SemesterList/AddSemesterModal/AddSemesterModal.module.scss, src/pages/TimetablePage/components/SemesterList/AddSemesterModal/index.tsx, src/pages/TimetablePage/hooks/useSelect.ts, src/pages/TimetablePage/hooks/useSemesterOptionList.ts, src/pages/TimetablePage/hooks/useTakenLectureCode.ts
- Close #698 
- 기능 : 학적 정보 관련 로직 수정과 Listbox --> Selector로 refactor
- issue : #698 
- `Listbox` 대신 새로 만든 공통 컴포넌트인 `Selector`로 리팩터링했습니다.
=> [졸업학점계산기] 학적 정보 입력 폼 수정

src/pages/TimetablePage/components/CustomLecture/index.tsx
- Close #707 
- 기능 :  커스텀 시간표 기능 중 요일 선택이 미 반영되는 이슈를 해결했습니다.
- issue : #707
=> [커스텀시간표] 요일 선택 이슈 해결

src/pages/Auth/SignupPage/index.tsx
- Close #711 
- 기능 : 회원가입 시 성별을 선택값으로 수정했습니다.
- issue : #711
=> [유저] 회원가입 시 성별 선택값으로

index.html, src/components/common/LogPage/index.tsx
- Close #716 
- 기능 : user_id 할당값 수정
- issue : #716 
<최종 user_id 값 및 할당 조건>
로그인 및 학번 존재 시 --> (학번 앞 여섯자리)_(id 값)
예) '202018_123'
로그인 및 학번 없을 시 --> ‘anonymous’_(id 값)
예) 'anonymous_123'
비로그인 유저 --> 아예 빈 값 ‘’
예) ''
=> [유저] user_id 할당값 수정

src/pages/GraduationCalculatorPage/GraduationCalculatorPage.module.scss, src/pages/GraduationCalculatorPage/components/ExcelUploader/index.tsx, src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx, src/pages/GraduationCalculatorPage/index.tsx
- Close #713
- 기능 : 툴팁 추가 및 첫 입장시 모달 펼치기
- issue : #713
=> [졸업학점계산기] QA 이슈 수정

src/pages/GraduationCalculatorPage/CalculatorHelpModal/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx, src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss, src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx, src/pages/GraduationCalculatorPage/index.tsx, src/utils/hooks/ui/useScrollLock.ts
- Close #724 
- 기능 : 툴팁 디자인 수정 및 모달 스크롤 방지 훅 구현
- issue : #724
=> [졸업학점계산기] 툴팁 디자인 수정 및 모달 스크롤 방지 훅 구현

src/pages/IndexPage/components/IndexStore/index.tsx, src/pages/Store/StorePage/components/EventCarousel/index.tsx
- 기능 : 주변상점 인덱스 페이지 코드 리팩토링
- issue : #734
비즈니스 코드 적응의 일환으로 코드 리팩토링을 진행하였습니다.
해당 pr에서는 인덱스 페이지 주변상점 컴포넌트를 리팩토링하였습니다.
* tsx에서 조건문 삭제
* 로직 부분에서 조건에 따른 미리 리스트 생성
=> [비즈니스] 주변상점 인덱스 페이지 코드 리팩토링

src/components/common/Footer/index.tsx, src/components/common/Header/PCHeader/index.tsx, src/pages/GraduationCalculatorPage/index.tsx, src/pages/TimetablePage/components/MainTimetable/index.tsx
- Close #735 
- 기능 : 
- issue : #735
=> [졸업학점계산기] 진입시와 탈출시 로깅 추가

src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/index.tsx, src/pages/GraduationCalculatorPage/components/CourseTable/DeleteLectureModal/index.tsx, src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx, src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx, src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/index.tsx, src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx, src/pages/GraduationCalculatorPage/hooks/useExcelUpload.ts, src/pages/TimetablePage/components/SemesterList/index.tsx
- Close #736 
- 기능 : 졸업학점계산기 내부 이벤트 로깅을 추가합니다.
- issue : #736
=> [졸업학점계산기] 내부 로깅 추가

src/components/common/Toast/TimetableToast/TimetableToast.module.scss, src/pages/Auth/ModifyInfoPage/index.tsx, src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss, src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss, src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx, src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx, src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss, src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx, src/pages/GraduationCalculatorPage/index.tsx, src/pages/TimetablePage/hooks/useAllMyLectures.ts, src/pages/TimetablePage/hooks/useTotalGrades.ts
- Close #746 
- 기능 :  마지막 QA 사항 해결입니다.
- issue : #746 
- 비로그인 상태로 졸학계 페이지 진입 시 401 에러가 나지 않게 했습니다.
- 강의 테이블 높이를 수정했습니다.
=> [졸업학점계산기] 마지막 QA 이슈 해결

src/pages/Store/StoreDetailPage/components/MenuTable/MenuTable.module.scss, src/pages/Store/StoreDetailPage/components/MenuTable/index.tsx
- Close #753 
- 기능 : 메뉴 카테고리 변경 지점과 위치를 수정했습니다.
- issue : #753 
- 메뉴 카테고리가 스크롤해도 상단에 고정되어 있게 위치를 수정했습니다.
- 스크롤 시 해당 메뉴 카테고리에 맞는 카테고리로 자동 변경되도록 픽셀을 수정했습니다.
https://github.com/user-attachments/assets/5733812c-a79f-4845-b05d-d2a0308e6cea
=> [비지니스] 주변상점 메뉴 카테고리 변경 수정

src/api/articles/APIDetail.ts, src/pages/Articles/LostItemChatPage/LostItemChatPage.module.scss, src/pages/Articles/LostItemChatPage/index.tsx, src/pages/Articles/LostItemDetailPage/index.tsx, src/pages/Articles/LostItemWritePage/components/LostItemForm/LostItemForm.module.scss, src/pages/Articles/LostItemWritePage/components/LostItemForm/index.tsx, src/pages/Articles/hooks/usePostLostItemArticles.ts, src/pages/Articles/hooks/useSingleLostItemArticle.ts
- Close #761 
- 기능 : 모바일 공지사항 QA 수정하였습니다.
- issue : #761 
- 글 작성 후 완료 토스트가 뜹니다.
- 습득물 1개 일때에는 지우기 버튼이 나타나지 않습니다.
- 내가 쓴 글일 경우 쪽지 보내기/신고하기 버튼 대신 삭제 버튼이 나타납니다.
- 쪽지 보내기 모바일 뷰를 비율을 수정하여 채팅방이 보이도록 하였습니다.
<br />
<br />
<br />
=> [캠퍼스] 모바일 공지사항 QA 수정

src/pages/Bus/BusCoursePage/components/BusTimetableDetail/BusTimetableDetail.module.scss, src/pages/Bus/BusCoursePage/components/BusTimetableDetail/index.tsx, src/pages/Bus/BusCoursePage/components/Timetable/Timetable.module.scss, src/pages/Bus/BusCoursePage/components/Timetable/index.tsx
- Close #760 
- 기능 : 모바일 버스 QA 수정했습니다.
- issue : #760 
* 하단 인포 UI 수정
* 글자 겹침 해결
* 스크롤 기능 추가
=> [캠퍼스] 모바일 버스 QA 수정

src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
- Close #765 
- 기능 : 모바일 식단 QA 수정했습니다.
- issue : #765 
학식 금액이 없을 시(조식 토스트) • 표시 제거
=> [캠퍼스] 모바일 식단 QA 수정

src/components/layout/Header/MobileHeader/Panel/index.tsx, src/pages/Bus/BusCoursePage/components/BusTimetable/index.tsx, src/pages/Bus/BusCoursePage/components/BusTimetableDetail/index.tsx, src/pages/Bus/BusCoursePage/index.tsx, src/pages/Bus/BusRoutePage/index.tsx, src/pages/Bus/components/BusNotice/index.tsx, src/pages/IndexPage/components/IndexBus/index.tsx, src/static/bus.ts
- Close #769 
- 기능 :  버스 로깅을 추가하였습니다.
- issue : #769 
https://www.notion.so/1be9ae650b5980d5b6d8cf5b6ef8858c?pvs=4
관련 노션입니다.
명세에 나와있는 필요 버스 로깅을 모두 추가하였습니다.
[섹션]
- 메인_버스/교통
- 헤더/푸터/햄버거_버스/교통
- 버스 시간표
=> [캠퍼스] 버스 로깅 최신 반영

src/App.tsx, src/pages/Articles/LostItemDetailPage/components/Checkbox/Checkbox.module.scss, src/pages/Articles/LostItemDetailPage/components/Checkbox/index.tsx, src/pages/Articles/LostItemDetailPage/components/ReportForm/ReportForm.module.scss, src/pages/Articles/LostItemDetailPage/components/ReportForm/index.tsx, src/pages/Articles/LostItemDetailPage/components/ReportModal/ReportModal.module.scss, src/pages/Articles/LostItemDetailPage/components/ReportModal/index.tsx, src/pages/Articles/LostItemDetailPage/index.tsx, src/pages/Articles/ReportPage/ReportPage.module.scss, src/pages/Articles/ReportPage/index.tsx, src/pages/Articles/hooks/useReportLostItemArticle.ts, src/static/routes.ts
- 기능 : 공지사항 핫픽스
- issue : 
1.  모바일에서는 신고 모달이 아닌 페이지로 보이도록 수정
2.  placeholder 텍스트와 내용 텍스트 색 변경
3.  신고 후 자동 새로고침 오류 수정
4. 기타 내용 textarea 스크롤 경험 수정
=> [캠퍼스] 공지사항 핫픽스

src/pages/Store/StoreDetailPage/hooks/useDeleteReview.ts, src/pages/Store/StoreReviewPage/hooks/useAddStoreReview.ts
- Close #774 
- 기능 : 리뷰 개수가 바로바로 반영됨
- issue : #774
리뷰 개수가 바로바로 반영됨
=> [비지니스] 리뷰 개수 QA (#774) 해결

.vscode/settings.json, src/pages/Store/StoreDetailPage/components/Review/components/SelectButton/SelectButton.module.scss, src/pages/Store/StoreDetailPage/components/Review/components/SelectButton/SelectButton.tsx, src/pages/Store/StorePage/components/EventCarousel/hooks/useCarouselController.ts, src/pages/Store/StorePage/components/EventCarousel/index.tsx, src/pages/Store/StorePage/components/hooks/useGetAllEvents.ts
- 기능 : 
- issue : #
* 이벤트 carousel 컴포넌트 리팩토링
* 복잡하게 얽혀 있던 컴포넌트들 일괄적으로 처리
* 리뷰 수정하기, 삭제하기 svg 크기 이상함 이슈 해결
* 모바일에서는 리뷰 신고, 수정, 삭제에 svg를 사용하지 않고 있지 않음 + 피그마에서 리뷰 관련 ui를 찾을 수 없음
* 따라서 svg를 삭제하는 것으로 진행함
위 내용과는 별개로 vscode 업데이트 후 svg가 이미지로 열리는 것에 대해 코드와 이미지가 같이 열리도록 설정을 수정했습니다.
=> [비즈니스] 비즈니스 qa 이슈 해결 및 이벤트 관련 부분 리팩토링

src/pages/TimetablePage/components/CustomLecture/index.tsx
- Close #789 
- 기능 : undefined 객체에 접근하려고 할 때 발생하는 런타임 오류 수정
- issue : #789
=> [시간표] undefined 에러 수정

src/pages/Store/StoreReviewPage/hooks/useEditStoreReview.ts
- Close #785 
- 기능 : 리뷰 수정으로 바뀐 데이터가 바로바로 적용됨
- issue : #785
=> [비지니스] 리뷰 수정 QA(#785) 해결

src/api/banner/APIDetail.ts, src/api/banner/entity.ts, src/api/banner/index.ts, src/api/index.ts, src/components/ui/Banner/Banner.module.scss, src/components/ui/Banner/hooks/useBannerCategories.ts, src/components/ui/Banner/hooks/useBanners.ts, src/components/ui/Banner/index.tsx, src/pages/IndexPage/index.tsx
- Close #787 
- 기능 : 배너 기능을 추가하였습니다.
- issue : #787 
- 배너 API를 연결하였습니다.
- 배너 '일주일 동안 보지 않기' 및 '닫기' 버튼을 활성화 하였습니다.
- 배너 사진 좌 우 넘김(클릭, 화살표 키)을 추가하였습니다.
=> [캠퍼스] 배너 기능 추가

src/components/ui/Banner/Banner.module.scss, src/components/ui/Banner/index.tsx, src/components/ui/BannerB/BannerB.module.scss, src/components/ui/BannerB/index.tsx
- Close #802 
- 기능 : 배너 모바일뷰를 추가하였습니다.
- issue : #802
=> [캠퍼스] 배너 모바일뷰 추가

src/components/ui/Banner/Banner.module.scss, src/components/ui/Banner/index.tsx, src/components/ui/BannerB/BannerB.module.scss, src/components/ui/BannerB/index.tsx
- Close #805 
- 기능 : 배너 QA 이슈를 해결합니다.
- issue : #805 
- 배경 클릭을 활성화하였습니다.
- 링크 없는 배너는 클릭을 비활성화하였습니다. (커서도 클릭모드 X)
- 닫기 버튼의 session storage를 삭제하였습니다. (동일한 세션 안에서는 닫기 버튼 클릭해도 배너 나타나도록)
=> [캠퍼스] 배너 QA 이슈 수정

src/components/ui/Banner/index.tsx, src/components/ui/BannerB/index.tsx
- 기능 : 배너 로깅 값을 수정하였습니다.
배너의 다음 버튼 클릭 로깅 값을 수정하였습니다.
main_modal_next_modal -> main_next_modal
=> [캠퍼스] 배너 로깅 값 수정

src/api/auth/APIDetail.ts, src/api/auth/entity.ts, src/api/auth/index.ts
- Close #838 
- 기능 : api 엔드포인트 변경
- issue : #838 
변경된 api 엔드포인트와 필드명을 수정합니다.
**필드명 변경**
[ user_id → login_id ]
/v2/user/student/register Request
/v2/user/general/register Request
**엔드포인트 변경**
[ /user→ /users, /student → /students ]
/v2/user/student/register → /v2/users/students/register
/v2/user/general/register → /v2/users/register (general 삭제도 함께)
/user/verification/sms/send → /users/verification/sms/send
/user/verification/sms/verify → /users/verification/sms/verify
=> refactor: 엔드포인트 수정 및 필드명 수정

src/pages/Auth/SignupPage/Steps/StudentDetailStep/StudentDetailStep.module.scss, src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx, src/pages/Auth/SignupPage/components/CustomSelector/CustomSelector.module.scss
- Close #826 
- 기능 : 회원가입 - 정보입력 Web UI를 구현하였습니다.
- issue : #826 
브랜치 최신화를 위해 ui만 만들고 pr 올립니다.
버튼의 기능들은 구현하지 않았습니다.
ui만 봐주시면 감사하겠습니다!
버튼 기능 추가와 입력값 오류 처리는 다음 pr에서 진행할 예정입니다.
정보입력 ui입니다.
=> [유저] 회원가입 정보입력(학생) UI 구현

src/pages/Auth/SignupPage/components/CustomInput/index.tsx
- Close #847 
- 기능 : customInput 콘솔 에러 수정
- issue : #847
=> [유저] customInput 콘솔 에러 수정

src/App.tsx, src/pages/Auth/FindIdPage/PC/EmailPage/FindIdEmailPage.module.scss, src/pages/Auth/FindIdPage/PC/EmailPage/index.tsx, src/pages/Auth/FindIdPage/PC/PhonePage/FindIdPhonePage.module.scss, src/pages/Auth/FindIdPage/PC/PhonePage/index.tsx, src/pages/Auth/FindIdPage/PC/ResultPage/ResultPage.module.scss, src/pages/Auth/FindIdPage/PC/ResultPage/index.tsx, src/pages/Auth/FindIdPage/PC/index.tsx, src/utils/hooks/auth/usePhoneVerification.ts
- Close #872 
- 기능 : 
- issue : #872
=> [유저] PC 화면 아이디 찾기 구현

src/pages/Club/ClubDetailPage/components/ClubQnA/index.tsx, src/pages/Club/ClubDetailPage/components/ClubQnACard/index.tsx, src/pages/Club/ClubDetailPage/components/CreateQnAModal/index.tsx, src/pages/Club/ClubDetailPage/hooks/useClubManager.ts, src/pages/Club/ClubDetailPage/index.tsx, src/pages/Club/NewClubPage/components/AdditionalInfoModal/index.tsx, src/pages/Club/NewClubPage/components/MobileView/index.tsx, src/pages/Club/NewClubPage/components/PCView/index.tsx
- 기능 : 누락 로깅 추가
- issue : #
1. 동아리 상세 페이지 로깅 추가
2. Q&A 로깅 추가
3. 동아리 생성, 수정 로깅 추가
=> fix : 누락 로깅 추가

src/api/auth/APIDetail.ts, src/api/auth/entity.ts, src/api/auth/index.ts, src/pages/Auth/FindPasswordPage/PC/PCResetPasswordPhone/PCResetPasswordPhone.module.scss, src/pages/Auth/FindPasswordPage/PC/PCResetPasswordPhone/index.tsx, src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/PCVerifyPhone.module.scss, src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/index.tsx, src/pages/Auth/FindPasswordPage/index.tsx, src/static/auth.ts, src/utils/hooks/auth/usePhoneVerification.ts
- Close #882
- 기능 : 비밀번호 찾기 - 휴대전화 인증 플로우 UI 구현입니다.
- issue : #882 
비밀번호 찾기 - 휴대전화 인증 플로우 UI를 구현하였습니다.
테스트 가능 아이디와 전화번호입니다.
* ID: teststudent2
* PW: 01018188182
코드가 길어져 완료 페이지 UI는 포함하지 않았습니다.
=> [유저] 비밀번호 찾기 휴대전화 인증 플로우 UI 구현

src/assets/svg/orenge-check.svg, src/pages/Auth/FindPasswordPage/Complete/Complete.module.scss, src/pages/Auth/FindPasswordPage/Complete/index.tsx, src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/PCVerifyPhone.module.scss
- Close #887 
- 기능 : 비밀번호 변경 완료 페이지 추가
- issue : #887 
비밀번호 변경 완료 페이지를 추가하였습니다.
(좌측 PC, 우측 모바일)
=> [유저] 비밀번호 변경 완료 페이지 추가

src/pages/Auth/FindIdPage/Mobile/EmailPage/index.tsx, src/pages/Auth/FindIdPage/Mobile/PhonePage/index.tsx, src/pages/Auth/FindIdPage/PC/EmailPage/index.tsx, src/pages/Auth/FindIdPage/PC/PhonePage/index.tsx, src/pages/Auth/FindPasswordPage/Mobile/MobileVerifyEmail/index.tsx, src/pages/Auth/FindPasswordPage/Mobile/MobileVerifyPhone/index.tsx, src/pages/Auth/FindPasswordPage/PC/PCVerifyEmail/index.tsx, src/pages/Auth/FindPasswordPage/PC/PCVerifyPhone/index.tsx, src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx, src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx, src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx, src/utils/hooks/auth/useEmailVerification.ts, src/utils/hooks/auth/usePhoneVerification.ts, src/utils/hooks/auth/usePhoneVerificationInFindId.ts
- Close #913 
- 기능 : 
- issue : #913 
- 불필요한 상태 제거 (pr 리뷰 반영)
- 회원가입 : 남은 횟수 하드 코딩 삭제
- 회원가입 : 이름 조건 만족되지 않더라도 전화번호 인증 되면 다음 버튼 활성화되는 이슈 수정
- ID 찾기 : 전화번호 글자수 제한
=> [유저] 아이디 찾기 및 회원가입 모바일 qa이슈 수정

src/components/layout/Header/MobileHeader/Panel/Panel.module.scss, src/components/modal/Modal/ImageModal/ImageModal.module.scss, src/components/modal/Modal/ImageModal/index.tsx, src/utils/ts/touchHandler.ts
- Close #922 
- 기능 :  모바일 웹 버전 사이드 네비바 스크롤 기능, 주변상점 소개 이미지 확대 기능 추가
- issue : #922
https://github.com/user-attachments/assets/9c8b0545-cf53-4316-bfc1-39ef34d8c709
https://github.com/user-attachments/assets/0f84396f-135f-4dfb-896f-001b25bbd120
=> [hotfix] 모바일 웹 버그 수정

src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx, src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx, src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx, src/pages/Auth/SignupPage/Steps/Terms/index.tsx, src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx, src/pages/Auth/SignupPage/index.tsx, src/utils/hooks/auth/usePhoneVerification.ts, src/utils/hooks/auth/useUserInfoUpdate.ts
- 기능 : 세션로깅 적용 및 정보수정 로깅 추가
회원가입 절차에 세션로깅 적용
정보수정 성공 및 실패 시 로깅 추가
=> [유저] 세션로깅 적용 및 정보수정 로깅 추가

src/App.tsx, src/utils/hooks/auth/useAuth.ts, src/utils/hooks/auth/useAutoLogin.ts
- Close #970
- 기능 : 자동 로그인을 이용한 로그인을 했음에도 브라우저를 껐다가 다시 접속 시 로그인 유지되지 않는 버그 수정
- issue : #970
https://github.com/user-attachments/assets/37fa91a3-33aa-4487-a0e6-b46986bba207
=> [hotfix] 자동 로그인 시 로그인 유지 기능 오류

src/pages/Bus/BusCoursePage/components/Timetable/index.tsx, src/pages/Bus/BusRoutePage/components/TimeDetail/TimeDetailMobile/index.tsx, src/pages/Bus/BusRoutePage/components/TimeDetail/TimeDetailPC/index.tsx, src/pages/Bus/BusRoutePage/hooks/useSemester.ts
- Close #981 
- 기능 : 
- issue : #981
학기 변경에 따른 시간표 제공 기간을 변경했습니다.
=> [hotfix] 학기 변경에 따른 버스 시간표 기간 변경

src/pages/Auth/LoginPage/hooks/useLogin.ts
- Close #986 
- 기능 : 버그 수정
- issue : #986
로그인 중 비밀번호에 대한 검증 없이 아이디에 대한 검증만 두 번 이루어지고 있어 해당 부분 수정했습니다.
=> [로그인] 로그인 과정 유효성 검증 오류 수정

src/components/IndexComponents/IndexCafeteria/index.tsx, src/components/cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss, src/components/cafeteria/MobileCafeteriaPage/index.tsx, src/components/cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss, src/components/cafeteria/PCCafeteriaPage/index.tsx, src/utils/hooks/analytics/useSessionLogger.ts
- Close #997 
- 기능 : AB 테스트용 버튼 추가& 세션 로깅
=> [식단과 식당] A/B테스트용 로깅버튼 추가 

package.json
- 기능 : 서버에서 실행할 next 스크립트 추가
- start:serve 스크립트 추가
=> [chore] start:serve 스크립트 추가

src/pages/Store/StorePage/components/SearchBar/index.tsx, src/pages/Store/StorePage/components/SearchBarModal/index.tsx, src/pages/Store/StorePage/index.tsx
- 기능 : 로깅 에러 수정
- 카테고리 id값을 idx로 넣어 잘못된 값을 로깅함
- 카테고리 이름이 아닌 id로 로깅함
=> [hotfix] 로깅 에러 수정
